-- Generated by tools/build_rule_data.py; edit the research JSON and rebuild.
-- Offline, inert Lua 5.1 data. Sources and fixtures are excluded.
local _, NS = ...
NS.Data = {
    ["dataset_id"] = "forever-clean-chat-commercial-spam-research",
    ["dataset_version"] = "2026-09-30.1",
    ["decision_rules"] = {
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R001_KNOWN_HOST",
            ["priority"] = 10,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "known_seller_domain",
            ["when"] = {
                ["feature"] = "known_domain_exact",
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R002_OBFUSCATED_HOST",
            ["priority"] = 20,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "known_seller_domain_obfuscated",
            ["when"] = {
                ["feature"] = "known_domain_obfuscated",
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R010_BRAND_AD",
            ["priority"] = 30,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "brand_commercial_context",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "known_brand_alias",
                    },
                    {
                        ["any"] = {
                            {
                                ["feature"] = "seller_intent",
                            },
                            {
                                ["feature"] = "merchant_cta",
                            },
                        },
                    },
                    {
                        ["any"] = {
                            {
                                ["feature"] = "gold_commodity_offer",
                            },
                            {
                                ["feature"] = "offered_boost",
                            },
                            {
                                ["feature"] = "offered_game_service",
                            },
                            {
                                ["feature"] = "wow_account_offer",
                            },
                        },
                    },
                    {
                        ["any"] = {
                            {
                                ["feature"] = "money_anchor",
                            },
                            {
                                ["feature"] = "external_destination",
                            },
                            {
                                ["feature"] = "promotion_evidence",
                            },
                        },
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R020_GOLD_CASH",
            ["priority"] = 40,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "real_money_gold_offer",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "gold_commodity_offer",
                    },
                    {
                        ["feature"] = "money_anchor",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R021_SERVICE_CASH",
            ["priority"] = 41,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "real_money_service_offer",
            ["when"] = {
                ["all"] = {
                    {
                        ["any"] = {
                            {
                                ["feature"] = "offered_boost",
                            },
                            {
                                ["feature"] = "offered_game_service",
                            },
                        },
                    },
                    {
                        ["feature"] = "money_anchor",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R022_GOLD_EXTERNAL",
            ["priority"] = 42,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "gold_offer_external_destination",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "gold_commodity_offer",
                    },
                    {
                        ["feature"] = "external_destination",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R023_GOLD_MARKETING",
            ["priority"] = 43,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "gold_offer_multiple_sales_hooks",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "gold_commodity_offer",
                    },
                    {
                        ["gte"] = 2,
                        ["metric"] = "distinct_promotion_families",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R024_CATALOGUE_PREORDER",
            ["priority"] = 44,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "preorder_service_catalogue",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "preorder_hook",
                    },
                    {
                        ["feature"] = "merchant_cta",
                    },
                    {
                        ["gte"] = 2,
                        ["metric"] = "distinct_offered_service_families",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R025_SERVICE_STOREFRONT",
            ["priority"] = 45,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "service_ad_external_marketing",
            ["when"] = {
                ["all"] = {
                    {
                        ["any"] = {
                            {
                                ["feature"] = "offered_game_service",
                            },
                            {
                                ["feature"] = "offered_boost",
                            },
                        },
                    },
                    {
                        ["any"] = {
                            {
                                ["feature"] = "seller_intent",
                            },
                            {
                                ["feature"] = "merchant_cta",
                            },
                        },
                    },
                    {
                        ["feature"] = "external_destination",
                    },
                    {
                        ["feature"] = "promotion_evidence",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R026_ACCOUNT_COMMERCE",
            ["priority"] = 46,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "account_sale_ad",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "wow_account_offer",
                    },
                    {
                        ["any"] = {
                            {
                                ["feature"] = "money_anchor",
                            },
                            {
                                ["feature"] = "external_destination",
                            },
                            {
                                ["feature"] = "merchant_cta",
                            },
                        },
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R027_CATALOGUE_MARKETING",
            ["priority"] = 47,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "multi_service_catalogue_marketing",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "seller_intent",
                    },
                    {
                        ["gte"] = 3,
                        ["metric"] = "distinct_offered_service_families",
                    },
                    {
                        ["feature"] = "promotion_evidence",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R100_PAID_BOOST",
            ["priority"] = 100,
            ["profiles"] = {
                "strict",
            },
            ["reason_code"] = "paid_or_sold_boost_offer",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "offered_boost",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "free_help_only",
                        },
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                    {
                        ["not"] = {
                            ["feature"] = "buyer_request_only",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R101_SERVICE_RATE",
            ["priority"] = 101,
            ["profiles"] = {
                "strict",
            },
            ["reason_code"] = "priced_progression_service",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "offered_game_service",
                    },
                    {
                        ["feature"] = "service_rate",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "free_help_only",
                        },
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R102_GOLD_SALE",
            ["priority"] = 102,
            ["profiles"] = {
                "strict",
            },
            ["reason_code"] = "gold_commodity_sale",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "gold_commodity_offer",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                    {
                        ["not"] = {
                            ["feature"] = "buyer_request_only",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "block",
            ["enabled"] = true,
            ["id"] = "R103_ACCOUNT_SALE",
            ["priority"] = 103,
            ["profiles"] = {
                "strict",
            },
            ["reason_code"] = "account_sale_offer",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "wow_account_offer",
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                    {
                        ["not"] = {
                            ["feature"] = "buyer_request_only",
                        },
                    },
                },
            },
        },
        {
            ["action"] = "review_only",
            ["enabled"] = false,
            ["id"] = "R190_COMMERCIAL_REPEAT_REVIEW",
            ["priority"] = 190,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "repeated_commercial_candidate",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "structured_repeat",
                    },
                    {
                        ["any"] = {
                            {
                                ["feature"] = "offered_boost",
                            },
                            {
                                ["feature"] = "gold_commodity_offer",
                            },
                            {
                                ["feature"] = "offered_game_service",
                            },
                        },
                    },
                },
            },
        },
        {
            ["action"] = "review_only",
            ["enabled"] = false,
            ["id"] = "R191_FUZZY_REVIEW",
            ["priority"] = 191,
            ["profiles"] = {
                "balanced",
                "strict",
            },
            ["reason_code"] = "unverified_near_domain",
            ["when"] = {
                ["all"] = {
                    {
                        ["feature"] = "fuzzy_domain_candidate",
                    },
                    {
                        ["any"] = {
                            {
                                ["feature"] = "seller_intent",
                            },
                            {
                                ["feature"] = "merchant_cta",
                            },
                        },
                    },
                },
            },
        },
    },
    ["domains"] = {
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_mythic_store_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "mythic-store.com",
            ["vendor_id"] = "mythic_store",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_skycoach_gg",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "skycoach.gg",
            ["vendor_id"] = "skycoach",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_overgear_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "overgear.com",
            ["vendor_id"] = "overgear",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_wowvendor_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "wowvendor.com",
            ["vendor_id"] = "wowvendor",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_blazingboost_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "blazingboost.com",
            ["vendor_id"] = "blazingboost",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_leprestore_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "leprestore.com",
            ["vendor_id"] = "leprestore",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_boosthive_eu",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "boosthive.eu",
            ["vendor_id"] = "boosthive",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_epiccarry_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "epiccarry.com",
            ["vendor_id"] = "epiccarry",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_wowcarry_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "wowcarry.com",
            ["vendor_id"] = "wowcarry",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_mmonster_co",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "mmonster.co",
            ["vendor_id"] = "mmonster",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_expcarry_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "expcarry.com",
            ["vendor_id"] = "expcarry",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_conquestcapped_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "conquestcapped.com",
            ["vendor_id"] = "conquestcapped",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_lfcarry_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "lfcarry.com",
            ["vendor_id"] = "lfcarry",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_simple_carry_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "simple-carry.com",
            ["vendor_id"] = "simple_carry",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_boosting_ground_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "boosting-ground.com",
            ["vendor_id"] = "boosting_ground",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_dving_net",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "dving.net",
            ["vendor_id"] = "dving",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_playerauctions_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "playerauctions.com",
            ["vendor_id"] = "playerauctions",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_eldorado_gg",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "eldorado.gg",
            ["vendor_id"] = "eldorado",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "indexed_primary_excerpt",
            ["id"] = "dom_g2g_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "g2g.com",
            ["vendor_id"] = "g2g",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_iggm_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "iggm.com",
            ["vendor_id"] = "iggm",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_mmoexp_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "mmoexp.com",
            ["vendor_id"] = "mmoexp",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_mmogah_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "mmogah.com",
            ["vendor_id"] = "mmogah",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "indexed_primary_excerpt",
            ["id"] = "dom_mmoga_de",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "mmoga.de",
            ["vendor_id"] = "mmoga",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_ssegold_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "ssegold.com",
            ["vendor_id"] = "ssegold",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_rpgstash_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "rpgstash.com",
            ["vendor_id"] = "rpgstash",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_u4gm_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "u4gm.com",
            ["vendor_id"] = "u4gm",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_z2u_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "z2u.com",
            ["vendor_id"] = "z2u",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_igv_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "igv.com",
            ["vendor_id"] = "igv",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_igvault_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "igvault.com",
            ["vendor_id"] = "igv",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_funpay_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "funpay.com",
            ["vendor_id"] = "funpay",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_lootbar_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "lootbar.com",
            ["vendor_id"] = "lootbar",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_lootbar_gg",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "lootbar.gg",
            ["vendor_id"] = "lootbar",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_g4mmo_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "g4mmo.com",
            ["vendor_id"] = "g4mmo",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_aoeah_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "aoeah.com",
            ["vendor_id"] = "aoeah",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_pvpbank_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "pvpbank.com",
            ["vendor_id"] = "pvpbank",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "retrieved_primary_content",
            ["id"] = "dom_odealo_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "odealo.com",
            ["vendor_id"] = "odealo",
        },
        {
            ["enabled"] = true,
            ["evidence_type"] = "user_observed_chat_ad",
            ["id"] = "dom_mythicstore_com",
            ["include_subdomains"] = true,
            ["infer_other_tlds"] = false,
            ["infer_typos_as_verified_domains"] = false,
            ["match_policy"] = "exact_host_or_bounded_text_obfuscation",
            ["preserve_canonical_digits"] = true,
            ["preserve_canonical_hyphens"] = true,
            ["type"] = "domain",
            ["value"] = "mythicstore.com",
            ["vendor_id"] = nil,
        },
    },
    ["external_destination_policy"] = {
        ["exact_commercial_invite_ids_verified"] = {},
        ["shared_platforms_not_blacklisted"] = {
            "discord.gg",
            "discord.com",
            "t.me",
            "telegram.me",
            "wa.me",
            "whatsapp.com",
            "bit.ly",
            "tinyurl.com",
            "youtube.com",
        },
    },
    ["feature_definitions"] = {
        {
            ["id"] = "known_domain_exact",
            ["lexicon_refs"] = {},
        },
        {
            ["id"] = "known_domain_obfuscated",
            ["lexicon_refs"] = {},
        },
        {
            ["id"] = "known_brand_alias",
            ["lexicon_refs"] = {},
        },
        {
            ["id"] = "seller_intent",
            ["lexicon_refs"] = {
                "seller_offer",
                "buyer_question",
                "negation_warning",
            },
        },
        {
            ["id"] = "merchant_cta",
            ["lexicon_refs"] = {
                "merchant_cta",
                "buyer_question",
                "negation_warning",
            },
        },
        {
            ["id"] = "gold_commodity_offer",
            ["lexicon_refs"] = {
                "gold_commodity",
                "seller_offer",
                "merchant_cta",
                "ordinary_trade",
            },
        },
        {
            ["id"] = "offered_boost",
            ["lexicon_refs"] = {
                "boost_explicit",
                "seller_offer",
                "ingame_rate",
                "unrelated_boost",
            },
        },
        {
            ["id"] = "offered_game_service",
            ["lexicon_refs"] = {
                "service_leveling",
                "service_dungeon",
                "service_raid",
                "service_gearing",
                "service_professions",
                "service_pvp",
                "service_collections",
            },
        },
        {
            ["id"] = "wow_account_offer",
            ["lexicon_refs"] = {
                "account_trade",
                "seller_offer",
                "merchant_cta",
            },
        },
        {
            ["id"] = "money_anchor",
            ["lexicon_refs"] = {
                "real_money",
            },
        },
        {
            ["id"] = "external_destination",
            ["lexicon_refs"] = {
                "external_contact_cue",
            },
        },
        {
            ["id"] = "service_rate",
            ["lexicon_refs"] = {
                "ingame_rate",
                "ordinary_trade",
            },
        },
        {
            ["id"] = "preorder_hook",
            ["lexicon_refs"] = {
                "promotion_urgency",
                "merchant_cta",
            },
        },
        {
            ["id"] = "promotion_evidence",
            ["lexicon_refs"] = {
                "promotion_price",
                "promotion_delivery",
                "promotion_trust",
                "promotion_convenience",
                "promotion_urgency",
            },
        },
        {
            ["id"] = "free_help_only",
            ["lexicon_refs"] = {
                "free_help",
            },
        },
        {
            ["id"] = "clear_local_warning",
            ["lexicon_refs"] = {
                "negation_warning",
            },
        },
        {
            ["id"] = "buyer_request_only",
            ["lexicon_refs"] = {
                "buyer_question",
            },
        },
        {
            ["id"] = "structured_repeat",
            ["lexicon_refs"] = {},
        },
        {
            ["id"] = "fuzzy_domain_candidate",
            ["lexicon_refs"] = {},
        },
    },
    ["lexical_templates"] = {
        {
            ["allowed_intervening_tokens"] = {
                "our",
                "your",
                "the",
                "cheap",
                "cheapest",
                "discounted",
                "wow",
                "classic",
                "forever",
                "retail",
                "fast",
            },
            ["id"] = "cta_buy_object",
            ["language"] = "en",
            ["max_intervening_tokens"] = 4,
            ["object_lexicon_refs"] = {
                "gold_commodity",
                "boost_explicit",
                "service_leveling",
                "service_dungeon",
                "service_raid",
                "service_gearing",
                "service_professions",
                "service_pvp",
                "service_collections",
            },
            ["produces"] = "merchant_cta",
            ["verb_tokens"] = {
                "buy",
                "order",
                "book",
                "reserve",
            },
        },
        {
            ["id"] = "brand_offers_object",
            ["language"] = "en",
            ["produces"] = "seller_intent",
            ["shape"] = "known_brand_alias + offers/provides/sells + 0..4 modifiers + service_or_gold",
        },
        {
            ["id"] = "for_sale_object",
            ["language"] = "en",
            ["produces"] = "seller_intent",
            ["shape"] = "gold/account/service object + for sale, or selling/WTS + object",
        },
    },
    ["lexicons"] = {
        {
            ["id"] = "seller_offer",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "verkaufe",
                    "wir verkaufen",
                    "wir bieten",
                },
                ["en"] = {
                    "wts",
                    "selling",
                    "we sell",
                    "we offer",
                    "we provide",
                    "we cover",
                    "our services",
                    "services available",
                    "boosts available",
                    "selling runs",
                    "available now",
                    "for sale",
                    "offers",
                    "selling services",
                },
                ["es"] = {
                    "vendo",
                    "vendemos",
                    "ofrecemos",
                },
                ["fr"] = {
                    "vends",
                    "nous vendons",
                    "nous proposons",
                },
                ["ru"] = {
                    "продам",
                    "продаем",
                    "предлагаем",
                },
                ["tr"] = {
                    "satılık",
                    "satilik",
                    "satıyoruz",
                    "satiyoruz",
                    "hizmet veriyoruz",
                    "boost satışı",
                    "boost satisi",
                },
            },
        },
        {
            ["id"] = "merchant_cta",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "jetzt kaufen",
                    "jetzt bestellen",
                    "gold kaufen",
                },
                ["en"] = {
                    "buy now",
                    "order now",
                    "shop now",
                    "book now",
                    "place your order",
                    "order today",
                    "visit our shop",
                    "visit our website",
                    "buy gold",
                    "buy wow gold",
                    "get your boost",
                    "reserve your spot",
                    "order for beta",
                    "pre-order",
                    "preorder",
                    "pre order",
                },
                ["es"] = {
                    "compra ahora",
                    "haz tu pedido",
                    "comprar oro",
                },
                ["fr"] = {
                    "achetez maintenant",
                    "commandez",
                    "acheter de l or",
                },
                ["ru"] = {
                    "купить золото",
                    "заказать",
                    "купи сейчас",
                },
                ["tr"] = {
                    "hemen satın al",
                    "hemen satin al",
                    "sipariş ver",
                    "siparis ver",
                    "ön sipariş",
                    "on siparis",
                    "sitemizi ziyaret et",
                },
            },
        },
        {
            ["id"] = "gold_commodity",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "wow gold",
                    "goldverkauf",
                },
                ["en"] = {
                    "gold",
                    "wow gold",
                    "cheap gold",
                    "buy gold",
                    "sell gold",
                    "gold for sale",
                    "gold delivery",
                    "g0ld",
                },
                ["es"] = {
                    "oro wow",
                    "venta de oro",
                },
                ["fr"] = {
                    "or wow",
                    "vente d or",
                },
                ["ru"] = {
                    "золото",
                    "голда",
                    "голду",
                },
                ["tr"] = {
                    "gold",
                    "oyun parası",
                    "oyun parasi",
                    "altın satışı",
                    "altin satisi",
                },
            },
        },
        {
            ["id"] = "boost_explicit",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "boost",
                    "boosting",
                },
                ["en"] = {
                    "boost",
                    "boosts",
                    "boosting",
                    "booster",
                    "carry",
                    "carries",
                    "carrying",
                    "b00st",
                    "b00sting",
                },
                ["es"] = {
                    "boost",
                    "carry",
                },
                ["fr"] = {
                    "boost",
                    "carry",
                },
                ["ru"] = {
                    "буст",
                    "бустинг",
                    "прокачка",
                },
                ["tr"] = {
                    "boost",
                    "taşıma hizmeti",
                    "tasima hizmeti",
                    "kasma hizmeti",
                },
            },
        },
        {
            ["id"] = "service_leveling",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "powerleveling",
                    "levelservice",
                },
                ["en"] = {
                    "leveling",
                    "levelling",
                    "powerleveling",
                    "power leveling",
                    "power levelling",
                    "level boost",
                    "leveling service",
                    "leveling package",
                },
                ["es"] = {
                    "subida de nivel",
                    "leveo",
                },
                ["fr"] = {
                    "leveling",
                    "montee de niveau",
                },
                ["ru"] = {
                    "прокачка персонажа",
                    "прокачка уровней",
                },
                ["tr"] = {
                    "level kasma",
                    "seviye kasma",
                },
            },
        },
        {
            ["id"] = "service_dungeon",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "dungeon",
                    "instanzen",
                },
                ["en"] = {
                    "dungeon",
                    "dungeons",
                    "dungeon boost",
                    "dungeon carry",
                    "mythic+",
                    "mythic plus",
                    "m+",
                    "keys",
                    "keystone",
                    "rfc",
                    "ragefire chasm",
                    "wc",
                    "wailing caverns",
                    "sfk",
                    "shadowfang keep",
                    "sm",
                    "scarlet monastery",
                    "mara",
                    "maraudon",
                    "stratholme",
                    "strat",
                },
                ["es"] = {
                    "mazmorras",
                    "mazmorra",
                },
                ["fr"] = {
                    "donjon",
                    "donjons",
                },
                ["ru"] = {
                    "подземелья",
                    "данжи",
                },
                ["tr"] = {
                    "zindan",
                    "dungeon",
                },
            },
        },
        {
            ["id"] = "service_raid",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "raid",
                    "schlachtzug",
                },
                ["en"] = {
                    "raid",
                    "raids",
                    "raid boost",
                    "raid carry",
                    "full clear",
                    "boss kill",
                    "heroic clear",
                    "mythic clear",
                    "loot run",
                    "aotc",
                    "ahead of the curve",
                    "cutting edge",
                },
                ["es"] = {
                    "raid",
                    "banda",
                },
                ["fr"] = {
                    "raid",
                },
                ["ru"] = {
                    "рейд",
                    "рейды",
                },
                ["tr"] = {
                    "raid",
                    "baskın",
                },
            },
        },
        {
            ["id"] = "service_gearing",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "ausrüstung boost",
                },
                ["en"] = {
                    "gearing",
                    "gear boost",
                    "gear service",
                    "gearing package",
                    "loot funnel",
                    "loot traders",
                    "armor stack",
                    "guaranteed loot",
                    "guaranteed gear",
                    "gearing service",
                },
                ["es"] = {
                    "servicio de equipo",
                },
                ["fr"] = {
                    "service equipement",
                },
                ["ru"] = {
                    "одевание персонажа",
                    "помощь с экипировкой",
                },
                ["tr"] = {
                    "gear kasma",
                    "eşya kasma",
                    "esya kasma",
                },
            },
        },
        {
            ["id"] = "service_professions",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "berufe leveln",
                },
                ["en"] = {
                    "professions",
                    "profession leveling",
                    "profession boost",
                    "profession package",
                    "max professions",
                },
                ["es"] = {
                    "subir profesiones",
                },
                ["fr"] = {
                    "monter les metiers",
                },
                ["ru"] = {
                    "прокачка профессий",
                },
                ["tr"] = {
                    "meslek kasma",
                    "meslek boost",
                },
            },
        },
        {
            ["id"] = "service_pvp",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "arena boost",
                    "wertung boost",
                },
                ["en"] = {
                    "pvp",
                    "arena boost",
                    "rating boost",
                    "arena carry",
                    "gladiator boost",
                    "honor farm",
                    "honour farm",
                    "rank boost",
                    "conquest farm",
                },
                ["es"] = {
                    "subir rating",
                },
                ["fr"] = {
                    "boost cote",
                },
                ["ru"] = {
                    "буст рейтинга",
                    "арена буст",
                },
                ["tr"] = {
                    "rating kasma",
                    "arena boost",
                },
            },
        },
        {
            ["id"] = "service_collections",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "reittier boost",
                },
                ["en"] = {
                    "mount boost",
                    "mount farm",
                    "achievement boost",
                    "achievement carry",
                    "reputation boost",
                    "renown boost",
                    "rep farm",
                    "attunement service",
                },
                ["es"] = {
                    "farm de monturas",
                },
                ["fr"] = {
                    "boost monture",
                },
                ["ru"] = {
                    "фарм маунтов",
                    "прокачка репутации",
                },
                ["tr"] = {
                    "binek kasma",
                    "reputation kasma",
                },
            },
        },
        {
            ["id"] = "account_trade",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "account verkaufen",
                    "account kaufen",
                },
                ["en"] = {
                    "account for sale",
                    "selling account",
                    "sell account",
                    "wow account",
                    "full access account",
                    "original owner",
                    "fresh account",
                    "max level account",
                },
                ["es"] = {
                    "cuenta en venta",
                    "venta de cuenta",
                },
                ["fr"] = {
                    "vente de compte",
                    "compte a vendre",
                },
                ["ru"] = {
                    "продам аккаунт",
                    "продажа аккаунтов",
                },
                ["tr"] = {
                    "hesap satılık",
                    "hesap satilik",
                    "hesap satışı",
                    "hesap satisi",
                },
            },
        },
        {
            ["id"] = "real_money",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "echtgeld",
                },
                ["en"] = {
                    "usd",
                    "eur",
                    "gbp",
                    "paypal",
                    "stripe",
                    "credit card",
                    "debit card",
                    "real money",
                    "cash payment",
                    "usdt",
                    "bitcoin",
                    "crypto",
                },
                ["es"] = {
                    "dinero real",
                },
                ["fr"] = {
                    "argent reel",
                },
                ["ru"] = {
                    "реальные деньги",
                    "рублей",
                    "руб",
                },
                ["tr"] = {
                    "gerçek para",
                    "gercek para",
                    "kredi kartı",
                    "kredi karti",
                },
            },
        },
        {
            ["id"] = "ingame_rate",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "pro run",
                },
                ["en"] = {
                    "gold only",
                    "gold per run",
                    "per run",
                    "per level",
                    "per dungeon",
                    "per boost",
                    "g/run",
                    "g per run",
                    "g/level",
                },
                ["es"] = {
                    "por run",
                },
                ["fr"] = {
                    "par run",
                },
                ["ru"] = {
                    "за заход",
                    "за уровень",
                },
                ["tr"] = {
                    "run başı",
                    "run basi",
                    "tur başı",
                    "tur basi",
                    "level başı",
                    "level basi",
                },
            },
        },
        {
            ["id"] = "promotion_price",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "günstig",
                    "gunstig",
                    "rabatt",
                    "rabattcode",
                },
                ["en"] = {
                    "cheap",
                    "cheapest",
                    "best price",
                    "lowest price",
                    "discount",
                    "coupon",
                    "promo code",
                    "use code",
                    "sale ends",
                    "special offer",
                    "bulk discount",
                    "volume discount",
                    "cashback",
                    "price match",
                },
                ["es"] = {
                    "barato",
                    "descuento",
                    "codigo promocional",
                },
                ["fr"] = {
                    "pas cher",
                    "reduction",
                    "code promo",
                },
                ["ru"] = {
                    "дешево",
                    "дёшево",
                    "скидка",
                    "промокод",
                },
                ["tr"] = {
                    "ucuz",
                    "indirim",
                    "kupon",
                    "promosyon kodu",
                },
            },
        },
        {
            ["id"] = "promotion_delivery",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "schnelle lieferung",
                    "sofort lieferbar",
                },
                ["en"] = {
                    "fast delivery",
                    "instant delivery",
                    "quick delivery",
                    "in stock",
                    "always in stock",
                    "24/7",
                    "24 7",
                    "24x7",
                    "live support",
                    "online support",
                    "instant start",
                    "start now",
                },
                ["es"] = {
                    "entrega rapida",
                    "entrega inmediata",
                },
                ["fr"] = {
                    "livraison rapide",
                    "livraison instantanee",
                },
                ["ru"] = {
                    "быстрая доставка",
                    "моментальная доставка",
                },
                ["tr"] = {
                    "hızlı teslimat",
                    "hizli teslimat",
                    "anında teslim",
                    "aninda teslim",
                    "7/24 destek",
                },
            },
        },
        {
            ["id"] = "promotion_trust",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "sichere lieferung",
                },
                ["en"] = {
                    "safe delivery",
                    "safe gold",
                    "hand farmed",
                    "hand-farmed",
                    "no bots",
                    "no ban",
                    "ban free",
                    "ban-free",
                    "100% safe",
                    "money back",
                    "money-back",
                    "refund guarantee",
                    "vpn protection",
                    "guaranteed result",
                    "trusted seller",
                    "verified seller",
                },
                ["es"] = {
                    "entrega segura",
                },
                ["fr"] = {
                    "livraison securisee",
                },
                ["ru"] = {
                    "гарантия возврата",
                    "безопасная доставка",
                },
                ["tr"] = {
                    "güvenli teslimat",
                    "guvenli teslimat",
                    "iade garantisi",
                },
            },
        },
        {
            ["id"] = "promotion_convenience",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "afk",
                },
                ["en"] = {
                    "afk",
                    "fully afk",
                    "selfplay",
                    "self play",
                    "self-play",
                    "piloted",
                    "pilot mode",
                    "no effort",
                    "skip the grind",
                    "loot traders included",
                    "free traders",
                    "timer guaranteed",
                    "loot guaranteed",
                    "bundle",
                    "package",
                },
                ["es"] = {
                    "afk",
                },
                ["fr"] = {
                    "afk",
                },
                ["ru"] = {
                    "пилот",
                    "афк",
                },
                ["tr"] = {
                    "afk kal",
                    "paket hizmet",
                },
            },
        },
        {
            ["id"] = "promotion_urgency",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "vorbestellen",
                    "begrenzte zeit",
                },
                ["en"] = {
                    "release ready",
                    "launch ready",
                    "preorder",
                    "pre-order",
                    "pre order",
                    "order for beta",
                    "limited time",
                    "limited slots",
                    "last slots",
                    "book your slot",
                    "launch discount",
                    "beta offer",
                    "season start",
                    "sale ends today",
                },
                ["es"] = {
                    "precompra",
                    "plazas limitadas",
                },
                ["fr"] = {
                    "precommande",
                    "places limitees",
                },
                ["ru"] = {
                    "предзаказ",
                    "места ограничены",
                },
                ["tr"] = {
                    "ön sipariş",
                    "on siparis",
                    "son kontenjan",
                    "sınırlı süre",
                    "sinirli sure",
                },
            },
        },
        {
            ["id"] = "external_contact_cue",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "kontaktiere uns",
                },
                ["en"] = {
                    "discord",
                    "telegram",
                    "whatsapp",
                    "contact us",
                    "visit our site",
                    "add us",
                    "dm us",
                    "our website",
                },
                ["es"] = {
                    "contactanos",
                },
                ["fr"] = {
                    "contactez nous",
                },
                ["ru"] = {
                    "сайт",
                    "пиши в дискорд",
                },
                ["tr"] = {
                    "discord",
                    "telegram",
                    "bize ulaş",
                    "bize ulas",
                    "sitemiz",
                },
            },
        },
        {
            ["id"] = "buyer_question",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "wo kaufen",
                },
                ["en"] = {
                    "wtb",
                    "looking to buy",
                    "anyone selling",
                    "does anyone sell",
                    "where can i buy",
                    "how do i buy",
                    "is it safe",
                    "has anyone used",
                    "anyone tried",
                },
                ["es"] = {
                    "donde comprar",
                },
                ["fr"] = {
                    "ou acheter",
                },
                ["ru"] = {
                    "где купить",
                    "кто продает",
                },
                ["tr"] = {
                    "alan var mı",
                    "alan var mi",
                    "nereden alırım",
                    "nereden alirim",
                    "güvenli mi",
                    "guvenli mi",
                    "kullanan var mı",
                    "kullanan var mi",
                },
            },
        },
        {
            ["id"] = "negation_warning",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "nicht kaufen",
                    "kein verkauf",
                },
                ["en"] = {
                    "do not",
                    "dont",
                    "don t",
                    "never",
                    "avoid",
                    "stop buying",
                    "stop selling",
                    "report gold sellers",
                    "report this spam",
                    "not selling",
                    "not for sale",
                    "no boosting",
                    "no boosts",
                },
                ["es"] = {
                    "no compres",
                    "no vendo",
                },
                ["fr"] = {
                    "ne pas acheter",
                },
                ["ru"] = {
                    "не покупайте",
                    "не продаю",
                },
                ["tr"] = {
                    "satmıyorum",
                    "satmiyorum",
                    "satılık değil",
                    "satilik degil",
                    "satın almayın",
                    "satin almayin",
                    "uzak durun",
                    "spamı bildir",
                    "spami bildir",
                },
            },
        },
        {
            ["id"] = "free_help",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "kostenlos helfen",
                },
                ["en"] = {
                    "free carry",
                    "free boost",
                    "helping for free",
                    "no payment",
                    "no charge",
                    "no gold needed",
                    "no gold required",
                    "no tips required",
                },
                ["es"] = {
                    "ayuda gratis",
                },
                ["fr"] = {
                    "aide gratuite",
                },
                ["ru"] = {
                    "бесплатно помогу",
                },
                ["tr"] = {
                    "ücretsiz yardım",
                    "ucretsiz yardim",
                    "bedava taşıma",
                    "bedava tasima",
                    "gold istemiyorum",
                },
            },
        },
        {
            ["id"] = "ordinary_trade",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "erze",
                    "leder",
                    "kräuter",
                    "krauter",
                    "verzauberung",
                },
                ["en"] = {
                    "copper bar",
                    "gold bar",
                    "iron bar",
                    "ore",
                    "leather",
                    "herbs",
                    "potions",
                    "enchant",
                    "enchanting",
                    "crafting",
                    "crafting order",
                    "your mats",
                    "my mats",
                    "tips appreciated",
                    "portals",
                    "portal",
                    "summon",
                    "summons",
                    "lockbox",
                    "bags",
                    "stack",
                    "per stack",
                    "gold ore",
                    "gold bars",
                    "profession journal",
                },
                ["es"] = {
                    "mena",
                    "cuero",
                    "encantamiento",
                },
                ["fr"] = {
                    "minerai",
                    "cuir",
                    "enchantement",
                },
                ["ru"] = {
                    "руда",
                    "кожа",
                    "зачарование",
                },
                ["tr"] = {
                    "maden",
                    "deri",
                    "iksir",
                    "malzeme",
                    "çuval",
                    "cuval",
                    "portal",
                },
            },
        },
        {
            ["id"] = "group_recruitment",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "suche gruppe",
                },
                ["en"] = {
                    "lfm",
                    "lfg",
                    "lf tank",
                    "lf healer",
                    "need tank",
                    "need healer",
                    "guild recruiting",
                    "looking for group",
                    "looking for more",
                    "guild run",
                    "casual guild",
                    "new players welcome",
                },
                ["es"] = {
                    "busco grupo",
                },
                ["fr"] = {
                    "cherche groupe",
                },
                ["ru"] = {
                    "ищу группу",
                    "нужен танк",
                },
                ["tr"] = {
                    "tank aranıyor",
                    "tank araniyor",
                    "healer aranıyor",
                    "healer araniyor",
                    "grup arıyorum",
                    "grup ariyorum",
                },
            },
        },
        {
            ["id"] = "unrelated_boost",
            ["match_unit"] = "bounded_phrase_or_token",
            ["standalone_block"] = false,
            ["terms_by_language"] = {
                ["de"] = {
                    "fps boost",
                },
                ["en"] = {
                    "fps boost",
                    "boost fps",
                    "performance boost",
                    "cpu boost",
                    "turbo boost",
                    "signal boost",
                    "damage boost",
                    "xp buff",
                    "experience buff",
                    "stat boost",
                },
                ["es"] = {
                    "mejorar fps",
                },
                ["fr"] = {
                    "boost fps",
                },
                ["ru"] = {
                    "повышение фпс",
                },
                ["tr"] = {
                    "fps artışı",
                    "fps artisi",
                    "performans artışı",
                    "performans artisi",
                },
            },
        },
    },
    ["marketing_hooks"] = {
        {
            ["id"] = "hook_price",
            ["lexicon_id"] = "promotion_price",
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_delivery",
            ["lexicon_id"] = "promotion_delivery",
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_support",
            ["lexicon_id"] = "promotion_delivery",
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_trust",
            ["lexicon_id"] = "promotion_trust",
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_afk",
            ["lexicon_id"] = "promotion_convenience",
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_playmode",
            ["lexicon_id"] = "promotion_convenience",
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_extras",
            ["lexicon_id"] = "promotion_convenience",
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_launch",
            ["lexicon_id"] = "promotion_urgency",
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_catalogue",
            ["lexicon_id"] = nil,
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_cta",
            ["lexicon_id"] = "merchant_cta",
            ["standalone_block"] = false,
        },
        {
            ["id"] = "hook_external",
            ["lexicon_id"] = "external_contact_cue",
            ["standalone_block"] = false,
        },
    },
    ["metrics"] = {
        {
            ["id"] = "distinct_promotion_families",
        },
        {
            ["id"] = "distinct_offered_service_families",
        },
    },
    ["normalization"] = {
        ["domain_boundary_contract"] = {
            ["do_not_expand_tlds"] = true,
            ["do_not_match_prefix_substrings"] = true,
            ["do_not_remove_hyphens_from_valid_unknown_ascii_hosts"] = true,
            ["include_paths_queries_as_domain_mentions"] = false,
            ["include_real_subdomains"] = true,
            ["include_url_userinfo_as_host"] = false,
            ["strip_known_www_prefix_only_when_parsing_host"] = true,
        },
        ["domain_transforms"] = {
            ["canonical_digits_never_replaced"] = true,
            ["casefold_ascii"] = true,
            ["dot_characters"] = {
                ".",
                "。",
                "．",
                "｡",
            },
            ["dot_words"] = {
                "dot",
                "[dot]",
                "(dot)",
                "{dot}",
                "nokta",
                "punkt",
                "punto",
            },
            ["format_characters_to_ignore_in_domain_candidate"] = {
                "U+200B",
                "U+200C",
                "U+200D",
                "U+2060",
                "U+FEFF",
                "U+00AD",
                "U+202A",
                "U+202B",
                "U+202C",
                "U+202D",
                "U+202E",
                "U+2066",
                "U+2067",
                "U+2068",
                "U+2069",
            },
            ["fullwidth_ascii"] = {
                ["from_codepoint_range"] = {
                    "U+FF01",
                    "U+FF5E",
                },
                ["offset_to_subtract"] = 65248,
            },
            ["leet_alternatives_for_canonical_ascii_letters"] = {
                ["a"] = {
                    "4",
                },
                ["e"] = {
                    "3",
                },
                ["i"] = {
                    "1",
                },
                ["o"] = {
                    "0",
                },
                ["s"] = {
                    "5",
                },
                ["t"] = {
                    "7",
                },
            },
            ["leet_applies_to"] = "registrable_label_only_not_tld",
            ["leet_max_substitutions"] = 2,
            ["leet_requires_commercial_context"] = true,
            ["preserve_structural_hyphens"] = true,
            ["selected_confusables"] = {
                ["a"] = {
                    "а",
                    "ɑ",
                },
                ["c"] = {
                    "с",
                    "ϲ",
                },
                ["e"] = {
                    "е",
                },
                ["h"] = {
                    "һ",
                },
                ["i"] = {
                    "і",
                    "ι",
                    "ı",
                },
                ["j"] = {
                    "ј",
                },
                ["o"] = {
                    "о",
                    "ο",
                },
                ["p"] = {
                    "р",
                    "ρ",
                },
                ["s"] = {
                    "ѕ",
                },
                ["x"] = {
                    "х",
                    "χ",
                },
                ["y"] = {
                    "у",
                    "υ",
                },
            },
        },
        ["fuzzy_matching"] = {
            ["enabled_by_default"] = false,
            ["hard_block_allowed"] = false,
            ["max_edit_distance"] = 1,
            ["minimum_label_length"] = 8,
            ["requires_merchant_context"] = true,
        },
        ["max_candidate_visible_codepoints"] = 128,
        ["max_domain_candidates"] = 32,
        ["max_separator_codepoints_between_signature_characters"] = 3,
        ["message_max_bytes"] = 4096,
        ["semantic_rules"] = {
            ["ad_segment_linking"] = {
                ["max_adjacent_clauses"] = 3,
                ["max_total_content_tokens"] = 64,
            },
            ["clause_scope_max_content_tokens"] = 24,
            ["global_leet_folding"] = false,
            ["language_support"] = {
                "en",
                "tr",
                "de",
                "fr",
                "es",
                "ru",
            },
            ["offer_object_max_token_distance"] = 12,
        },
    },
    ["numeric_parsers"] = {
        ["ingame_amount_units"] = {
            "g",
            "gold",
            "k gold",
            "kg",
            "k g",
        },
        ["rate_unit_aliases"] = {
            "run",
            "runs",
            "level",
            "levels",
            "dungeon",
            "dungeons",
            "boost",
            "boosts",
        },
        ["real_money_symbols"] = {
            ["$"] = "dollar_unspecified",
            ["US$"] = "USD",
            ["£"] = "GBP",
            ["€"] = "EUR",
            ["₺"] = "TRY",
            ["₽"] = "RUB",
        },
        ["real_money_units"] = {
            "usd",
            "eur",
            "gbp",
            "try",
            "tl",
            "rub",
            "cad",
            "aud",
        },
        ["service_rate_shapes"] = {
            "AMOUNTg/run",
            "AMOUNTg per run",
            "AMOUNT gold per level",
            "AMOUNTg/level",
            "AMOUNT gold per dungeon",
        },
        ["standalone_block"] = false,
    },
    ["profiles"] = {
        ["balanced"] = {
            ["block_buyer_requests"] = false,
            ["block_gold_paid_boosts"] = false,
            ["known_domain_mention_policy"] = "hide_all",
        },
        ["default_new_install"] = "strict",
        ["known_domain_policy_options"] = {
            ["contextual_gate"] = {
                ["all"] = {
                    {
                        ["any"] = {
                            {
                                ["feature"] = "seller_intent",
                            },
                            {
                                ["feature"] = "merchant_cta",
                            },
                        },
                    },
                    {
                        ["any"] = {
                            {
                                ["feature"] = "gold_commodity_offer",
                            },
                            {
                                ["feature"] = "offered_boost",
                            },
                            {
                                ["feature"] = "offered_game_service",
                            },
                            {
                                ["feature"] = "wow_account_offer",
                            },
                        },
                    },
                    {
                        ["not"] = {
                            ["feature"] = "clear_local_warning",
                        },
                    },
                },
            },
        },
        ["preserve_existing_mode_on_upgrade"] = true,
        ["recommended_for_this_user"] = "strict",
        ["strict"] = {
            ["block_buyer_requests"] = false,
            ["block_gold_paid_boosts"] = true,
            ["known_domain_mention_policy"] = "hide_all",
        },
    },
    ["schema_version"] = "1.0.0",
    ["vendors"] = {
        {
            ["generated_text_aliases"] = {
                "Mythic Store",
                "Mythic-Store",
            },
            ["id"] = "mythic_store",
            ["name"] = "Mythic Store",
        },
        {
            ["generated_text_aliases"] = {
                "Skycoach",
                "Sky Coach",
            },
            ["id"] = "skycoach",
            ["name"] = "Skycoach",
        },
        {
            ["generated_text_aliases"] = {
                "Overgear",
            },
            ["id"] = "overgear",
            ["name"] = "Overgear",
        },
        {
            ["generated_text_aliases"] = {
                "WowVendor",
                "WoW Vendor",
            },
            ["id"] = "wowvendor",
            ["name"] = "WowVendor",
        },
        {
            ["generated_text_aliases"] = {
                "BlazingBoost",
                "Blazing Boost",
            },
            ["id"] = "blazingboost",
            ["name"] = "BlazingBoost",
        },
        {
            ["generated_text_aliases"] = {
                "LepreStore",
                "Lepre Store",
            },
            ["id"] = "leprestore",
            ["name"] = "LepreStore",
        },
        {
            ["generated_text_aliases"] = {
                "Boosthive",
                "Boost Hive",
            },
            ["id"] = "boosthive",
            ["name"] = "Boosthive",
        },
        {
            ["generated_text_aliases"] = {
                "Epiccarry",
                "Epic Carry",
            },
            ["id"] = "epiccarry",
            ["name"] = "Epiccarry",
        },
        {
            ["generated_text_aliases"] = {
                "WowCarry",
                "WoW Carry",
            },
            ["id"] = "wowcarry",
            ["name"] = "WowCarry",
        },
        {
            ["generated_text_aliases"] = {
                "Mmonster",
            },
            ["id"] = "mmonster",
            ["name"] = "Mmonster",
        },
        {
            ["generated_text_aliases"] = {
                "ExpCarry",
                "Exp Carry",
            },
            ["id"] = "expcarry",
            ["name"] = "ExpCarry",
        },
        {
            ["generated_text_aliases"] = {
                "ConquestCapped",
                "Conquest Capped",
            },
            ["id"] = "conquestcapped",
            ["name"] = "ConquestCapped",
        },
        {
            ["generated_text_aliases"] = {
                "LFCarry",
                "LF Carry",
            },
            ["id"] = "lfcarry",
            ["name"] = "LFCarry",
        },
        {
            ["generated_text_aliases"] = {
                "Simple Carry",
                "Simple-Carry",
            },
            ["id"] = "simple_carry",
            ["name"] = "Simple Carry",
        },
        {
            ["generated_text_aliases"] = {
                "Boosting Ground",
                "Boosting-Ground",
            },
            ["id"] = "boosting_ground",
            ["name"] = "Boosting Ground",
        },
        {
            ["generated_text_aliases"] = {
                "Dving",
            },
            ["id"] = "dving",
            ["name"] = "Dving",
        },
        {
            ["generated_text_aliases"] = {
                "PlayerAuctions",
                "Player Auctions",
            },
            ["id"] = "playerauctions",
            ["name"] = "PlayerAuctions",
        },
        {
            ["generated_text_aliases"] = {
                "Eldorado",
            },
            ["id"] = "eldorado",
            ["name"] = "Eldorado",
        },
        {
            ["generated_text_aliases"] = {
                "G2G",
            },
            ["id"] = "g2g",
            ["name"] = "G2G",
        },
        {
            ["generated_text_aliases"] = {
                "IGGM",
            },
            ["id"] = "iggm",
            ["name"] = "IGGM",
        },
        {
            ["generated_text_aliases"] = {
                "MMOexp",
                "MMO Exp",
            },
            ["id"] = "mmoexp",
            ["name"] = "MMOexp",
        },
        {
            ["generated_text_aliases"] = {
                "MmoGah",
                "MMO Gah",
            },
            ["id"] = "mmogah",
            ["name"] = "MmoGah",
        },
        {
            ["generated_text_aliases"] = {
                "MMOGA",
            },
            ["id"] = "mmoga",
            ["name"] = "MMOGA",
        },
        {
            ["generated_text_aliases"] = {
                "SSEGold",
                "SSE Gold",
            },
            ["id"] = "ssegold",
            ["name"] = "SSEGold",
        },
        {
            ["generated_text_aliases"] = {
                "RPGStash",
                "RPG Stash",
            },
            ["id"] = "rpgstash",
            ["name"] = "RPGStash",
        },
        {
            ["generated_text_aliases"] = {
                "U4GM",
            },
            ["id"] = "u4gm",
            ["name"] = "U4GM",
        },
        {
            ["generated_text_aliases"] = {
                "Z2U",
            },
            ["id"] = "z2u",
            ["name"] = "Z2U",
        },
        {
            ["generated_text_aliases"] = {
                "iGV",
                "iGVault",
                "iG Vault",
            },
            ["id"] = "igv",
            ["name"] = "iGV / iGVault",
        },
        {
            ["generated_text_aliases"] = {
                "FunPay",
                "Fun Pay",
            },
            ["id"] = "funpay",
            ["name"] = "FunPay",
        },
        {
            ["generated_text_aliases"] = {
                "LootBar",
                "Loot Bar",
            },
            ["id"] = "lootbar",
            ["name"] = "LootBar",
        },
        {
            ["generated_text_aliases"] = {
                "G4MMO",
                "G4 MMO",
            },
            ["id"] = "g4mmo",
            ["name"] = "G4MMO",
        },
        {
            ["generated_text_aliases"] = {
                "AOEAH",
            },
            ["id"] = "aoeah",
            ["name"] = "AOEAH",
        },
        {
            ["generated_text_aliases"] = {
                "PVPBank",
                "PVP Bank",
            },
            ["id"] = "pvpbank",
            ["name"] = "PVPBank",
        },
        {
            ["generated_text_aliases"] = {
                "Odealo",
            },
            ["id"] = "odealo",
            ["name"] = "Odealo",
        },
    },
}
