-- Actual production callbacks run on stateful native WoW frame doubles.
-- This suite never sends chat and cannot confirm rendering in the target client.
local root=arg[1] or '.'
local H=assert(loadfile(root..'/tests/harness_ui.lua'))()
local report={suite='ui',runtime=_VERSION,total=0,passed=0,failed=0,failures={},checks={},
    native_rendering='not_run',target_client='not_run'}
local label='setup'
local function eq(actual,expected,description)
    report.total=report.total+1
    if actual~=expected then
        report.failed=report.failed+1
        local text=(description or 'assertion')..': '..tostring(actual)..' expected '..tostring(expected)
        report.failures[#report.failures+1]={id=label,description=description,actual=tostring(actual),expected=tostring(expected)}
        error(text,2)
    end
    report.passed=report.passed+1
end
local function truth(actual,description) eq(actual==true,true,description) end
local function near(actual,expected,tolerance,description)
    truth(type(actual)=='number' and math.abs(actual-expected)<=(tolerance or .001),description)
end
local function contains(text,value) return string.find(text or '',value,1,true)~=nil end
local function fresh(saved,options)
    local e,ns=H.uiGame('modern',saved,options)
    e:boot()
    return e,ns
end
local function open(e,ns,tab)
    ns.UI.Show(tab or 'overview')
    truth(ns.UI.frame and ns.UI.frame:IsShown(),'control panel visible')
    return ns.UI.controls
end
local function chooseKind(e,c,kind)
    e:click(c.listsKinds[kind]);e:input(c.listSearch,'')
end
local function selectEntry(e,c,key)
    e:input(c.listSearch,key)
    eq(c.listRows[1].entry.key,key,'search finds exact list entry')
    e:click(c.listRows[1])
end
local function captionButton(parent,text)
    for _,child in ipairs(parent.children or {}) do
        if child.kind=='Button' and child.caption and child.caption:GetText()==text then return child end
    end
    error('missing button caption '..text)
end
local function group(name,callback)
    label=name
    local beforeFailed,beforeTotal=report.failed,report.total
    local ok,err=pcall(callback)
    if not ok and report.failed==beforeFailed then
        report.total=report.total+1;report.failed=report.failed+1
        report.failures[#report.failures+1]={id=name,description=tostring(err)}
    end
    report.checks[#report.checks+1]={id=name,status=ok and 'passed_mock' or 'failed',
        assertions=report.total-beforeTotal,error=not ok and tostring(err) or nil}
    if not ok then print('FAIL UI '..name..': '..tostring(err)) end
end

group('startup_and_panel_navigation',function()
    local e,ns=fresh()
    eq(ns.installed,true,'filter installed before UI interaction')
    eq(e.addCalls,5,'one registration per supported chat event')
    eq(ns.UI.frame,nil,'panel built lazily')
    truth(ns.Minimap.button and ns.Minimap.button:IsShown(),'minimap visible by default')
    for _,frame in ipairs(e.frames) do eq(frame.scripts.OnUpdate,nil,'startup has no OnUpdate polling') end
    e:cmd('')
    truth(ns.UI.frame:IsShown(),'empty /fcc opens panel')
    eq(ns.UI.tab,'overview','default overview tab')
    eq(ns.db.ui.language,'en','English preference')
    local c=ns.UI.controls
    for _,tab in ipairs({'log','lists','settings','test','overview'}) do
        eq(c.tabs[tab]:IsVisible(),false,'advanced navigation hidden on home: '..tab)
    end
    truth(c.homeMessages:IsVisible(),'home message shortcut visible')
    truth(c.homeAdvanced:IsVisible(),'home advanced shortcut visible')
    e:click(c.homeAdvanced);eq(ns.UI.tab,'settings','advanced shortcut opens settings')
    for _,tab in ipairs({'log','lists','settings','test','overview'}) do
        e:click(c.tabs[tab]);eq(ns.UI.tab,tab,'tab click selects '..tab)
    end
    for _,tab in ipairs({'log','lists','settings','test'}) do
        e:click(c.homeAdvanced);e:click(c.tabs[tab]);e:click(c.backHome)
        eq(ns.UI.tab,'overview','back home returns from '..tab)
        truth(c.homeAdvanced:IsVisible(),'home access restored after '..tab)
    end
    e:click(c.close);eq(ns.UI.frame:IsShown(),false,'close button hides panel')
    e:cmd('');truth(ns.UI.frame:IsShown(),'slash reopens panel')
    e:escape();eq(ns.UI.frame:IsShown(),false,'Escape through UISpecialFrames hides panel')
    e:cmd('settings');eq(ns.UI.tab,'settings','settings slash opens settings')
    truth(ns.UI.frame:IsShown(),'settings slash shows panel')
    ns.UI.Hide();eq(ns.UI.frame:IsShown(),false,'public Hide')
end)

group('minimap_click_tooltip_and_visibility',function()
    local e,ns=fresh()
    local b=ns.Minimap.button
    e:click(b,'LeftButton');truth(ns.UI.frame:IsShown(),'left click opens panel')
    e:click(b,'LeftButton');eq(ns.UI.frame:IsShown(),false,'second left click toggles panel')
    e:click(b,'RightButton');eq(ns.UI.tab,'settings','right click opens settings')
    e:fire(b,'OnEnter');truth(e.GameTooltip:IsShown(),'hover tooltip shown')
    local lines={}
    for _,line in ipairs(e.GameTooltip.lines) do lines[#lines+1]=line[1] end
    local tooltip=table.concat(lines,'\n')
    truth(contains(tooltip,'Forever Clean Chat'),'tooltip title')
    truth(contains(tooltip,'Hidden this session:'),'tooltip counters')
    truth(contains(tooltip,'Right-click: open settings'),'tooltip right click instruction')
    e:fire(b,'OnLeave');eq(e.GameTooltip:IsShown(),false,'leave hides tooltip')
    local c=ns.UI.controls
    e:click(c.minimap);eq(ns.db.ui.minimap.hide,true,'setting stores hidden minimap')
    eq(b:IsShown(),false,'setting hides button immediately')
    e:click(c.minimap);eq(ns.db.ui.minimap.hide,false,'setting restores minimap')
    truth(b:IsShown(),'button restored immediately')
    e:cmd('minimap hide');eq(b:IsShown(),false,'slash hides minimap')
    e:cmd('minimap show');truth(b:IsShown(),'slash restores minimap')
    eq(b.scripts.OnUpdate,nil,'minimap has no idle polling')
end)

group('overview_controls_and_shortcuts',function()
    local e,ns=fresh()
    local c=open(e,ns,'overview')
    e:click(c.overviewBalanced);eq(ns.db.mode,'balanced','overview selects balanced')
    e:click(c.overviewStrict);eq(ns.db.mode,'strict','overview selects strict')
    e:click(c.overviewToggle);eq(ns.db.enabled,false,'overview pauses protection')
    e:click(c.overviewToggle);eq(ns.db.enabled,true,'overview resumes protection')
    e:click(c.homeMessages)
    eq(ns.UI.tab,'log','overview log shortcut')
    e:click(c.backHome)
    e:click(c.homeAdvanced);e:click(c.tabs.test)
    eq(ns.UI.tab,'test','overview local test shortcut')
    c.testInput:SetFocus();e:input(c.testInput,'LFM healer')
    e:fire(c.testInput,'OnEscapePressed')
    eq(ns.UI.frame:IsShown(),false,'focused edit Escape closes panel')
    eq(c.testInput:HasFocus(),false,'Escape clears focus')
end)

group('home_live_protection_state_and_count',function()
    local e,ns=fresh()
    local c=open(e,ns,'overview')
    local p=ns.UI.panels.overview
    eq(p.status:GetText(),'Active','fresh home describes protection state')
    eq(c.overviewToggle.caption:GetText(),'ON','fresh home switch on')
    eq(p.hiddenCounter:GetText(),'0','fresh home count comes from empty session')
    truth(p.status.textColor[2]>p.status.textColor[1],'active state is visibly green')
    eq(p.statusDot,nil,'old status lamp is removed')
    truth(p.protectionLock~=nil,'home protection state has a padlock')
    eq(c.protectionLock,p.protectionLock,'padlock is exposed as the home control')
    eq(p.protectionLock.phase,'closed','initial active lock is closed')
    truth(e:chat('mythicstore.com','Example Seller-Realm',9801),'actual incoming callback hides known host')
    eq(p.hiddenCounter:GetText(),'1','visible counter refreshes after real callback')
    truth(e:chat('mythicstore.com','Example Seller-Realm',9801),'repeat callback remains hidden')
    eq(p.hiddenCounter:GetText(),'1','duplicate message does not inflate home count')
    e:click(c.overviewToggle)
    eq(p.status:GetText(),'Paused','home reflects paused state')
    eq(c.overviewToggle.caption:GetText(),'OFF','switch caption reflects paused state')
    truth(p.status.textColor[1]>p.status.textColor[2],'paused state is visibly distinct')
    eq(p.protectionLock.enabled,false,'paused padlock targets disabled state')
    eq(p.protectionLock.phase,'opening','pausing raises the padlock shackle first')
    eq(e:chat('mythicstore.com',nil,9802),false,'home switch immediately permits incoming chat')
    eq(p.hiddenCounter:GetText(),'1','pausing does not reset session history')
    e:click(c.overviewToggle)
    e:click(c.overviewBalanced)
    eq(e:chat('WTS RFC boosts 5g/run',nil,9803),false,'home balanced selector immediately changes filter')
    truth(contains(p.modeDescription:GetText(),'advertising'),'balanced explanation reflects selected mode')
    e:click(c.overviewStrict)
    truth(e:chat('WTS RFC boosts 5g/run',nil,9804),'home strict selector immediately changes filter')
    truth(contains(p.modeDescription:GetText(),'boost'),'strict explanation reflects selected mode')
    eq(p.hiddenCounter:GetText(),'2','home counter reflects both hidden messages')
    e:click(c.homeMessages)
    eq(c.logRows[1].entry.message,'WTS RFC boosts 5g/run','home message action reaches actual session log')
end)

group('padlock_on_off_stage_order_and_idle_cleanup',function()
    local e,ns=fresh()
    local c=open(e,ns,'overview')
    local lock=c.protectionLock
    truth(lock~=nil,'home exposes animated protection lock')
    truth(lock.body~=nil and lock.shackle~=nil and lock.glow~=nil,'padlock exposes body, shackle and green glow')
    eq(lock.enabled,true,'initial lock reflects active protection')
    eq(lock.phase,'closed','opening the panel does not replay enable animation')
    eq(lock.visualAlpha,1,'active protection leaves lock visible')
    eq(lock.openAmount,0,'active protection has a lowered closed shackle')
    eq(lock.animating,false,'initial stable lock does not animate')
    eq(lock:GetScript('OnUpdate'),nil,'initial stable lock installs no polling')
    near(lock.durations.fadeIn,.5,nil,'ON fade-in lasts half a second')
    near(lock.durations.close,.24,nil,'closing shackle uses the defined brief travel')
    near(lock.durations.flash,.28,nil,'green flash has a finite brief duration')
    near(lock.durations.open,.24,nil,'opening shackle uses the defined brief travel')
    near(lock.durations.fadeOut,.35,nil,'OFF fade-out follows opening')
    local x,y,w,h=e:bounds(lock,ns.UI.panels.overview)
    truth(x>=0 and y>=0 and x+w<=ns.UI.panels.overview:GetWidth() and y+h<=106,'padlock stays inside protection card')
    truth(w>=28 and h>=38,'padlock has enough room for its body and moving shackle')
    local session,total,callbacks=ns.sessionBlocked,ns.db.totalBlocked,ns.callbackCount
    e:click(c.overviewToggle)
    eq(lock.phase,'opening','OFF begins by opening a visible closed lock')
    eq(lock.visualAlpha,1,'OFF does not fade before opening')
    eq(lock.openAmount,0,'OFF starts from the current closed shackle')
    e:advance(.12)
    truth(lock.openAmount>.4 and lock.openAmount<.6,'OFF midpoint raises shackle halfway')
    eq(lock.visualAlpha,1,'shackle opens before fade-out')
    e:advance(.121)
    eq(lock.phase,'fading_out','open lock now starts fading out')
    eq(lock.openAmount,1,'OFF fade begins with fully open shackle')
    e:advance(.174)
    near(lock.visualAlpha,.5,.02,'open lock fades gradually at OFF midpoint')
    eq(lock.openAmount,1,'fade-out keeps the shackle open')
    e:advance(.3)
    eq(lock.phase,'hidden','OFF finishes with hidden open lock')
    eq(lock.visualAlpha,0,'OFF disappears completely')
    eq(lock.openAmount,1,'invisible disabled lock remains open')
    eq(lock.animating,false,'OFF animation finishes')
    eq(lock:GetScript('OnUpdate'),nil,'OFF completion detaches per-frame callback')
    e:click(c.overviewToggle)
    eq(lock.phase,'fading_in','ON first reveals an open lock')
    eq(lock.visualAlpha,0,'ON fade starts fully transparent')
    eq(lock.openAmount,1,'ON fade starts with raised open shackle')
    e:advance(.25)
    near(lock.visualAlpha,.5,.015,'open lock reaches half opacity after 0.25 seconds')
    eq(lock.openAmount,1,'shackle stays open throughout fade-in')
    e:advance(.251)
    eq(lock.phase,'closing','ON closes only after the half-second reveal')
    near(lock.visualAlpha,1,nil,'ON closes a fully visible lock')
    e:advance(.119)
    truth(lock.openAmount>.4 and lock.openAmount<.6,'ON midpoint lowers shackle halfway')
    eq(lock.glow:GetAlpha(),0,'green flash waits for the closed shackle')
    e:advance(.122)
    eq(lock.phase,'glowing','closed lock gives a short green flash')
    eq(lock.openAmount,0,'green flash follows fully lowered shackle')
    e:advance(.06)
    truth(lock.glow:GetAlpha()>0,'green glow is visible during flash')
    e:advance(.3)
    eq(lock.phase,'closed','ON finishes as a persistent closed lock')
    eq(lock.visualAlpha,1,'closed lock remains visible after flash')
    eq(lock.openAmount,0,'persistent lock stays closed')
    eq(lock.glow:GetAlpha(),0,'brief flash does not remain permanently lit')
    eq(lock.animating,false,'ON animation finishes')
    eq(lock:GetScript('OnUpdate'),nil,'ON completion detaches per-frame callback')
    local calls=e.updateCalls
    e:advance(5)
    eq(e.updateCalls,calls,'stable lock has no idle animation updates')
    eq(lock.phase,'closed','elapsed idle time leaves active lock visible')
    eq(ns.sessionBlocked,session,'visual animation does not change session counter')
    eq(ns.db.totalBlocked,total,'visual animation does not change saved counter')
    eq(ns.callbackCount,callbacks,'visual animation does not synthesize chat callbacks')
    eq(e.SendChatMessage,nil,'lock animation never obtains an outbound chat API')
end)

group('padlock_rapid_reversal_preserves_current_visual_state',function()
    local e,ns=fresh({schema=2,enabled=false,mode='strict'})
    local c=open(e,ns,'overview')
    local lock=c.protectionLock
    eq(lock.phase,'hidden','saved disabled protection initially has a hidden lock')
    e:click(c.overviewToggle);e:advance(.21)
    local alpha,amount=lock.visualAlpha,lock.openAmount
    truth(alpha>0 and alpha<1,'first interrupted ON is midway through reveal')
    e:click(c.overviewToggle)
    near(lock.visualAlpha,alpha,nil,'OFF during fade-in preserves current opacity')
    near(lock.openAmount,amount,nil,'OFF during fade-in preserves current shackle position')
    e:advance(.05)
    truth(lock.visualAlpha<alpha,'reversed fade now approaches invisible OFF state')
    alpha,amount=lock.visualAlpha,lock.openAmount
    e:click(c.overviewToggle)
    near(lock.visualAlpha,alpha,nil,'second ON starts at current partially faded opacity')
    near(lock.openAmount,amount,nil,'second ON preserves open shackle')
    e:advance(1.2)
    eq(lock.phase,'closed','rapid fade reversals eventually reach final ON state')
    eq(lock:GetScript('OnUpdate'),nil,'reversed enable animation still completes')
    e:click(c.overviewToggle);e:advance(.7)
    e:click(c.overviewToggle);e:advance(.62)
    eq(lock.phase,'closing','next interruption occurs while closing shackle')
    alpha,amount=lock.visualAlpha,lock.openAmount
    truth(amount>0 and amount<1,'shackle is partway down before reversal')
    e:click(c.overviewToggle)
    near(lock.visualAlpha,alpha,nil,'OFF during closing preserves opacity')
    near(lock.openAmount,amount,nil,'OFF during closing does not jump to a closed endpoint')
    e:advance(.05)
    truth(lock.openAmount>amount,'reversed shackle now travels upward')
    alpha,amount=lock.visualAlpha,lock.openAmount
    e:click(c.overviewToggle)
    near(lock.visualAlpha,alpha,nil,'ON during opening preserves opacity')
    near(lock.openAmount,amount,nil,'ON during opening preserves raised amount')
    e:advance(1.2)
    eq(lock.phase,'closed','repeated shackle reversals settle to final enabled state')
    e:click(c.overviewToggle);e:advance(.12)
    alpha,amount=lock.visualAlpha,lock.openAmount
    e:click(c.overviewToggle)
    near(lock.visualAlpha,alpha,nil,'reversing OFF opening preserves current opacity')
    near(lock.openAmount,amount,nil,'reversing OFF opening preserves halfway-open shackle')
    e:advance(1.2)
    eq(lock.phase,'closed','reversed OFF opening finishes closed')
    e:click(c.overviewToggle);e:advance(.7)
    e:click(c.overviewToggle);e:advance(.78)
    eq(lock.phase,'glowing','last interruption occurs during ON flash')
    e:click(c.overviewToggle);e:advance(.8)
    eq(lock.phase,'hidden','OFF during flash finishes invisible and open')
    eq(lock.visualAlpha,0,'final disabled state remains transparent')
    eq(lock.openAmount,1,'final disabled state remains open')
    eq(lock.animating,false,'rapid reversals never strand an active animation')
    eq(lock:GetScript('OnUpdate'),nil,'rapid reversals leave no idle OnUpdate')
    eq(ns.db.enabled,false,'final user setting survives animation reversals')
end)

group('padlock_hidden_tabs_slash_minimap_and_close_settle_state',function()
    local e,ns=fresh()
    local c=open(e,ns,'overview')
    local lock=c.protectionLock
    e:cmd('off')
    eq(lock.phase,'opening','slash OFF animates while home is visible')
    e:advance(.09)
    e:click(c.homeAdvanced)
    eq(lock.phase,'hidden','leaving home settles hidden OFF lock immediately')
    eq(lock.animating,false,'hidden home stops its finite animation')
    eq(lock:GetScript('OnUpdate'),nil,'hidden home detaches OnUpdate')
    e:click(c.enabled)
    eq(ns.db.enabled,true,'advanced settings still enable protection')
    eq(lock.phase,'closed','hidden home adopts advanced settings without replaying')
    eq(lock:GetScript('OnUpdate'),nil,'advanced settings leave hidden lock idle')
    e:click(c.backHome)
    eq(lock.phase,'closed','returning home shows persistent closed current state')
    e:cmd('off');e:advance(.08)
    e:click(c.close)
    eq(lock.phase,'hidden','closing panel settles partial OFF animation')
    eq(lock:GetScript('OnUpdate'),nil,'closed panel has no lock polling')
    e:cmd('on')
    eq(lock.phase,'closed','hidden slash ON updates stable padlock state')
    eq(lock:GetScript('OnUpdate'),nil,'hidden slash setting does not start animation')
    e:click(ns.Minimap.button,'LeftButton')
    eq(ns.UI.tab,'overview','minimap reopens the home panel')
    eq(lock.phase,'closed','minimap opens current stable enabled lock')
    eq(lock.visualAlpha,1,'minimap reopens visible active lock')
    e:cmd('off');e:advance(.07);e:escape()
    eq(lock.phase,'hidden','Escape settles interrupted OFF animation')
    eq(lock:GetScript('OnUpdate'),nil,'Escape removes lock animation callback')
    e:click(ns.Minimap.button,'RightButton')
    eq(ns.UI.tab,'settings','minimap right-click opens settings')
    e:click(c.enabled);e:click(c.backHome)
    eq(lock.phase,'closed','settings accessed by minimap produce correct persistent home lock')
    local other,reloaded=fresh(H.copy(ns.db))
    local controls=open(other,reloaded,'overview')
    eq(controls.protectionLock.phase,'closed','saved enabled preference restores stable lock after reload')
    eq(controls.protectionLock:GetScript('OnUpdate'),nil,'reloaded stable lock has no polling')
    truth(other:chat('mythicstore.com',nil,9851),'reload retains actual protection filtering')
    eq(other:chat('LFM healer',nil,9852),false,'animation integration preserves ordinary chat')
end)

group('padlock_finite_overshoot_idempotence_and_native_fallback',function()
    local e,ns=fresh({schema=2,enabled=false,mode='balanced'})
    local c=open(e,ns,'overview')
    local lock=c.protectionLock
    e:click(c.overviewToggle)
    e:advance(.1)
    local alpha,amount,phase=lock.visualAlpha,lock.openAmount,lock.phase
    ns.UI.Refresh()
    near(lock.visualAlpha,alpha,nil,'ordinary UI refresh preserves elapsed reveal opacity')
    near(lock.openAmount,amount,nil,'ordinary UI refresh preserves shackle position')
    eq(lock.phase,phase,'ordinary UI refresh does not restart active animation')
    truth(e:chat('mythicstore.com',nil,9861),'protection works during enable animation')
    near(lock.visualAlpha,alpha,nil,'real hidden-message counter refresh preserves animation opacity')
    near(lock.openAmount,amount,nil,'real hidden-message counter refresh preserves shackle position')
    eq(lock.phase,phase,'real hidden-message counter refresh does not restart animation')
    lock:SetEnabled(true,true)
    near(lock.visualAlpha,alpha,nil,'same target does not restart fade-in')
    near(lock.openAmount,amount,nil,'same target does not reset shackle')
    eq(lock.phase,phase,'same target preserves active phase')
    e:advance(2,2)
    eq(lock.phase,'closed','one slow frame consumes all pending ON stages')
    eq(lock.visualAlpha,1,'large frame delta finishes visible lock')
    eq(lock.openAmount,0,'large frame delta finishes closed shackle')
    eq(lock:GetScript('OnUpdate'),nil,'large frame delta still cleans up callback')
    lock:SetEnabled(false,true);e:advance(2,2)
    eq(lock.phase,'hidden','one slow frame consumes both OFF stages')
    eq(lock:GetScript('OnUpdate'),nil,'large OFF frame delta cleans up callback')
    lock:SetEnabled(true,false)
    eq(lock.phase,'closed','nonanimated synchronization immediately closes lock')
    eq(lock:GetScript('OnUpdate'),nil,'nonanimated synchronization creates no update callback')
    local fallback,other=fresh(nil,{noCreateLine=true})
    local controls=open(fallback,other,'overview')
    truth(controls.protectionLock.body~=nil and controls.protectionLock.shackle~=nil,'older native API still draws padlock')
    fallback:click(controls.overviewToggle);fallback:advance(.8)
    eq(controls.protectionLock.phase,'hidden','older native API completes OFF animation')
    fallback:click(controls.overviewToggle);fallback:advance(1.2)
    eq(controls.protectionLock.phase,'closed','older native API completes ON animation')
    eq(controls.protectionLock:GetScript('OnUpdate'),nil,'older native API has no idle polling')
end)

group('settings_immediately_change_filtering',function()
    local e,ns=fresh()
    local c=open(e,ns,'settings')
    truth(e:chat('mythicstore.com',nil,1001),'enabled hides known host')
    e:click(c.enabled);eq(ns.db.enabled,false,'enabled toggle off')
    eq(e:chat('mythicstore.com',nil,1002),false,'disabled allows same cached message')
    e:click(c.enabled);truth(ns.db.enabled,'enabled toggle on')
    e:click(c.balanced);eq(ns.db.mode,'balanced','balanced selected')
    eq(e:chat('WTS RFC boosts 5g/run',nil,1003),false,'balanced allows in-game paid boost')
    e:click(c.strict);eq(ns.db.mode,'strict','strict selected')
    truth(e:chat('WTS RFC boosts 5g/run',nil,1004),'strict blocks same text after invalidation')
    e:click(c.contextual);eq(ns.db.known_domain_mention_policy,'contextual','contextual selected')
    eq(e:chat('Avoid mythicstore.com advertisements',nil,1005),false,'contextual allows warning about known host')
    e:click(c.hideAll);eq(ns.db.known_domain_mention_policy,'hide_all','hide all selected')
    truth(e:chat('Avoid mythicstore.com advertisements',nil,1006),'hide all changes cached decision')
    for index,event in ipairs(ns.Events) do
        e:click(c.events[event]);eq(ns.db.chatEvents[event],false,'scope off '..event)
        eq(e:chat('mythicstore.com',nil,1100+index,nil,event),false,'disabled scope allows '..event)
        e:click(c.events[event]);eq(ns.db.chatEvents[event],true,'scope restored '..event)
        truth(e:chat('mythicstore.com',nil,1200+index,nil,event),'enabled scope blocks '..event)
    end
    eq(e.addCalls,5,'settings changes never duplicate filter installation')
    for _,frame in ipairs(e.frames) do eq(frame.scripts.OnUpdate,nil,'settings do not install polling') end
end)

group('lists_validate_edit_and_preserve_builtin_pack',function()
    local e,ns=fresh()
    local c=open(e,ns,'lists')
    local defaultCount=#ns.Data.domains
    e:click(c.listsKinds.domain)
    e:input(c.listInput,'not a domain');e:click(c.listAdd)
    eq(H.count(ns.db.domains),0,'invalid domain never stored')
    e:input(c.listInput,'https://www.Example.COM/path');e:click(c.listAdd)
    truth(ns.db.domains['example.com']~=nil,'domain input canonicalized')
    truth(e:chat('example.com',nil,2001),'custom domain changes filter')
    for _,domain in ipairs({'a-b.com','ab.com','a.b.com'}) do
        e:input(c.listInput,domain);e:click(c.listAdd)
        truth(ns.db.domains[domain]~=nil,'distinct structural domain '..domain)
    end
    selectEntry(e,c,'a-b.com');e:click(c.listRemove);e:input(c.listSearch,'')
    eq(ns.db.domains['a-b.com'],nil,'remove only requested domain')
    truth(ns.db.domains['ab.com']~=nil,'other domain retained')
    selectEntry(e,c,'mythicstore.com');e:click(c.listRemove);e:input(c.listSearch,'')
    eq(ns.db.domainDisabled['mythicstore.com'],true,'builtin removal is an exclusion')
    eq(#ns.Data.domains,defaultCount,'offline builtin pack unchanged')
    eq(e:chat('mythicstore.com',nil,2002),false,'excluded builtin host allowed')
    chooseKind(e,c,'phrase')
    e:input(c.listInput,'ab');e:click(c.listAdd);eq(H.count(ns.db.phrases),0,'short phrase rejected')
    e:input(c.listInput,'Custom Special Offer');e:click(c.listAdd)
    truth(ns.db.phrases['custom special offer'],'phrase normalized')
    truth(e:chat('Our custom special offer',nil,2003),'custom phrase hides')
    selectEntry(e,c,'custom special offer');e:click(c.listRemove)
    eq(e:chat('Our custom special offer',nil,2004),false,'phrase removal invalidates decision')
    chooseKind(e,c,'block');e:input(c.listInput,'Helpful Seller-Realm');e:click(c.listAdd)
    truth(ns.db.block['helpful seller-realm'],'manual block added')
    truth(e:chat('LFM healer','Helpful Seller-Realm',2005),'manually blocked player hidden')
    chooseKind(e,c,'allow');e:input(c.listInput,'Helpful Seller-Realm');e:click(c.listAdd)
    truth(ns.db.allow['helpful seller-realm'],'manual allow added')
    eq(ns.db.block['helpful seller-realm'],nil,'allow action resolves block conflict')
    eq(e:chat('example.com','Helpful Seller-Realm',2006),false,'allow player takes precedence')
    e:input(c.listInput,'Bad|Hname');e:click(c.listAdd)
    eq(H.count(ns.db.allow),1,'unsafe name rejected')
    chooseKind(e,c,'domainAllow');e:input(c.listInput,'example.com');e:click(c.listAdd)
    truth(ns.db.domainAllow['example.com'],'domain exception stored')
    eq(e:chat('example.com','Other Seller-Realm',2007),false,'domain exception immediate')
    selectEntry(e,c,'example.com');e:click(c.listRemove)
    truth(e:chat('example.com','Other Seller-Realm',2008),'exception removal immediate')
end)

group('lists_search_paging_and_row_selection',function()
    local e,ns=fresh()
    for index=1,20 do ns.Settings.EditList('domain','add','test'..string.format('%02d',index)..'.example') end
    local c=open(e,ns,'lists')
    e:click(c.listsKinds.domain)
    local first=c.listRows[1].caption:GetText()
    e:click(c.listNext)
    truth(c.listRows[1].caption:GetText()~=first,'next page changes first list row')
    e:click(c.listPrev);eq(c.listRows[1].caption:GetText(),first,'previous page restores rows')
    e:input(c.listSearch,'test17')
    truth(contains(c.listRows[1].caption:GetText(),'test17.example'),'search finds canonical domain')
    e:click(c.listRows[1])
    eq(ns.UI.listSelected.key,'test17.example','selection identifies chosen entry')
    e:click(c.listRemove);eq(ns.db.domains['test17.example'],nil,'remove selected row')
    e:input(c.listSearch,'')
    truth(c.listRows[1]:IsShown(),'cleared search restores rows')
end)

group('builtin_domain_toggle_works_with_full_personal_list',function()
    local e,ns=fresh()
    for index=1,100 do truth(ns.Settings.EditList('domain','add','custom'..index..'.example'),'custom entry '..index) end
    eq(H.count(ns.db.domains),100,'personal domain list filled')
    local c=open(e,ns,'lists')
    chooseKind(e,c,'domain');selectEntry(e,c,'mythicstore.com');e:click(c.listRemove)
    truth(ns.db.domainDisabled['mythicstore.com'],'builtin disabled at personal list cap')
    selectEntry(e,c,'mythicstore.com');e:click(c.listRemove)
    eq(ns.db.domainDisabled['mythicstore.com'],nil,'builtin reenabled at personal list cap')
    eq(H.count(ns.db.domains),100,'builtin toggle never consumes personal entry')
    truth(e:chat('mythicstore.com',nil,2901),'reenabled builtin filters immediately')
end)

group('hidden_log_bounded_paging_selection_and_actions',function()
    local e,ns=fresh()
    for index=1,60 do truth(e:chat('mythicstore.com','Seller '..index..'-Realm',3000+index),'sample hidden '..index) end
    eq(#ns.log,50,'log bounded to last 50')
    eq(ns.log[1].author,'Seller 11-Realm','oldest discarded')
    local c=open(e,ns,'log')
    local first=c.logRows[1].caption:GetText()
    truth(contains(first,'Seller 60'),'newest row first')
    e:click(c.logNext);truth(c.logRows[1].caption:GetText()~=first,'log next page')
    e:click(c.logPrev);eq(c.logRows[1].caption:GetText(),first,'log previous page')
    e:input(c.logSearch,'Seller 57-')
    eq(c.logRows[1].entry.author,'Seller 57-Realm','log search locates author')
    e:input(c.logSearch,'R001_KNOWN_HOST')
    truth(c.logRows[1]:IsShown(),'log search locates rule')
    e:input(c.logSearch,'nothing will match this')
    eq(c.logRows[1]:IsShown(),false,'no matching log row')
    e:input(c.logSearch,'')
    e:click(c.logRows[1]);e:click(c.logAllow)
    truth(ns.db.allow['seller 60-realm'],'selected author allowed')
    eq(e:chat('mythicstore.com','Seller 60-Realm',4001),false,'log allow immediately affects future chat')
    e:click(c.logBlock);truth(ns.db.block['seller 60-realm'],'selected author can be blocked')
    eq(ns.db.allow['seller 60-realm'],nil,'block action resolves allow conflict')
    truth(e:chat('Normal message','Seller 60-Realm',4002),'log block hides ordinary message')
    e:click(c.logRows[2]);e:click(c.logDomainAllow)
    truth(ns.db.domainAllow['mythicstore.com'],'selected domain exception')
    eq(e:chat('mythicstore.com','Unlisted Seller-Realm',4003),false,'domain exception affects other senders')
    local session,total=ns.sessionBlocked,ns.db.totalBlocked
    e:click(c.logClear);eq(#ns.log,0,'clear hides session records')
    eq(ns.sessionBlocked,session,'clear preserves session count')
    eq(ns.db.totalBlocked,total,'clear preserves total count')
end)

group('maximum_lifetime_counter_remains_valid_after_reload',function()
    local e,ns=fresh({schema=2,enabled=true,mode='strict',totalBlocked=1000000000000})
    truth(e:chat('mythicstore.com',nil,5001),'max-counter message hidden')
    eq(ns.db.totalBlocked,1000000000000,'lifetime counter saturates at valid maximum')
    eq(ns.sessionBlocked,1,'session counter still increments')
    local other,reloaded=fresh(H.copy(ns.db))
    eq(reloaded.db.totalBlocked,1000000000000,'reload preserves saturated lifetime count')
end)

group('long_message_detail_native_scroll_handlers',function()
    local e,ns=fresh()
    truth(e:chat('mythicstore.com '..string.rep('long sample ',100),nil,5201),'long host advertisement hidden')
    open(e,ns,'log')
    local detail=ns.UI.panels.log.detail
    truth(detail.scroll:GetVerticalScrollRange()>0,'long message has scroll range')
    e:click(captionButton(detail,'v'))
    truth(detail.scroll:GetVerticalScroll()>0,'down arrow scrolls detail')
    e:click(captionButton(detail,'^'))
    eq(detail.scroll:GetVerticalScroll(),0,'up arrow returns to top')
    e:fire(detail.scroll,'OnMouseWheel',-1)
    truth(detail.scroll:GetVerticalScroll()>0,'mouse wheel scrolls detail')
    e:fire(detail.scroll,'OnMouseWheel',-1000)
    eq(detail.scroll:GetVerticalScroll(),detail.scroll:GetVerticalScrollRange(),'scroll clamps to native range')
    e:fire(detail.scroll,'OnMouseWheel',1000)
    eq(detail.scroll:GetVerticalScroll(),0,'scroll clamps at top')
end)

group('local_test_tab_and_slash_never_send_or_count',function()
    local e,ns=fresh()
    local c=open(e,ns,'test')
    local session,total,callbacks=ns.sessionBlocked,ns.db.totalBlocked,ns.callbackCount
    e:input(c.testInput,'mythicstore.com');e:click(c.testRun)
    truth(ns.UI.lastTest.block,'known-host local sample HIDE')
    eq(ns.UI.lastTest.explanation.rule_id,'R001_KNOWN_HOST','local result shows structured rule')
    e:input(c.testInput,'WTS Copper Bar 2g per stack');e:click(c.testRun)
    eq(ns.UI.lastTest.block,false,'normal item local sample ALLOW')
    for index,button in ipairs(c.testSamples) do
        e:click(button)
        truth(#c.testInput:GetText()>0,'sample '..index..' populates local input')
        e:click(c.testRun)
        eq(type(ns.UI.lastTest.block),'boolean','sample '..index..' evaluates')
    end
    e:click(c.selfTest)
    e:cmd('test');e:cmd('why mythicstore.com')
    eq(ns.sessionBlocked,session,'local tests do not increase session counter')
    eq(ns.db.totalBlocked,total,'local tests do not increase saved counter')
    eq(ns.callbackCount,callbacks,'local tests never invoke incoming chat adapter')
    eq(#ns.log,0,'local tests do not populate hidden log')
    eq(e.SendChatMessage,nil,'harness never exposes outbound chat API')
end)

group('window_and_preferences_survive_reload',function()
    local saved={schema=2,enabled=false,mode='balanced',totalBlocked=23,
        domains={['private.example']='private.example'},phrases={['custom phrase']=true},
        allow={['trusted player-realm']=true},block={['bad player-realm']=true},
        domainDisabled={['mythicstore.com']=true},domainAllow={['wowgold.com']=true},
        known_domain_mention_policy='contextual',chatEvents={CHAT_MSG_WHISPER=false},
        ui={language='en',window={point='TOPLEFT',relativePoint='TOPLEFT',x=100,y=-120},minimap={hide=true,angle=77}}}
    local e,ns=fresh(H.copy(saved))
    eq(ns.db.enabled,false,'old enabled preserved');eq(ns.db.mode,'balanced','old mode preserved')
    eq(ns.db.totalBlocked,23,'old total preserved')
    truth(ns.db.domains['private.example']~=nil,'custom domain preserved')
    truth(ns.db.phrases['custom phrase'],'custom phrase preserved')
    truth(ns.db.allow['trusted player-realm'],'allow preserved');truth(ns.db.block['bad player-realm'],'block preserved')
    truth(ns.db.domainDisabled['mythicstore.com'],'builtin exclusion preserved')
    truth(ns.db.domainAllow['wowgold.com'],'domain exception preserved')
    eq(ns.db.chatEvents.CHAT_MSG_WHISPER,false,'scope preference preserved')
    eq(ns.Minimap.button:IsShown(),false,'hidden preference used at startup')
    local c=open(e,ns,'settings')
    local point,relative,relativePoint,x,y=ns.UI.frame:GetPoint()
    eq(point,'TOPLEFT','restored window point');eq(relativePoint,'TOPLEFT','restored relative point')
    eq(x,100,'restored x');eq(y,-120,'restored y')
    local dragHandle
    for _,child in ipairs(ns.UI.frame.children) do if child.scripts.OnDragStart then dragHandle=child;break end end
    truth(dragHandle~=nil,'window title bar has native drag handler')
    e:fire(dragHandle,'OnDragStart','LeftButton')
    ns.UI.frame:ClearAllPoints();ns.UI.frame:SetPoint('BOTTOMRIGHT',e.UIParent,'BOTTOMRIGHT',-85,90)
    e:fire(dragHandle,'OnDragStop')
    eq(ns.db.ui.window.x,-85,'window drag saves x');eq(ns.db.ui.window.y,90,'window drag saves y')
    local other,loaded=fresh(H.copy(ns.db));open(other,loaded,'settings')
    local nextPoint,_,nextRelative,nextX,nextY=loaded.UI.frame:GetPoint()
    eq(nextPoint,'BOTTOMRIGHT','reload window point');eq(nextRelative,'BOTTOMRIGHT','reload relative point')
    eq(nextX,-85,'reload x');eq(nextY,90,'reload y')
    other:click(loaded.UI.controls.resetWindow)
    eq(loaded.db.ui.window.point,'CENTER','reset saves center');eq(loaded.db.ui.window.x,0,'reset saves x')
    eq(loaded.db.mode,'balanced','window reset preserves mode')
    truth(loaded.db.allow['trusted player-realm'],'window reset preserves allow list')
end)

group('minimap_native_drag_angles_and_scaled_geometry',function()
    local e,ns=fresh()
    local b=ns.Minimap.button
    for _,sample in ipairs({{600,500,0},{500,600,90},{400,500,180},{500,400,270},{400,400,225}}) do
        e:fire(b,'OnMouseDown','LeftButton');e:fire(b,'OnDragStart')
        eq(b.moving,true,'native movement starts')
        local before=ns.db.ui.minimap.angle
        e.cursorX,e.cursorY=sample[1],sample[2]
        eq(ns.db.ui.minimap.angle,before,'angle is not polled while dragging')
        e:fire(b,'OnDragStop');eq(b.moving,false,'native movement ends')
        truth(math.abs(ns.db.ui.minimap.angle-sample[3])<0.0001,'saved quadrant angle '..sample[3])
        e:click(b,'LeftButton');eq(ns.UI.frame,nil,'drag-release click suppressed')
    end
    e.Minimap:SetScale(2);e.cursorX,e.cursorY=1200,1000
    e:fire(b,'OnMouseDown','LeftButton');e:fire(b,'OnDragStart');e:fire(b,'OnDragStop')
    truth(math.abs(ns.db.ui.minimap.angle)<0.0001,'scaled cursor converted to minimap coordinates')
    e.cursorX,e.cursorY=1000,1000
    local angle=ns.db.ui.minimap.angle
    e:fire(b,'OnMouseDown','LeftButton');e:fire(b,'OnDragStart');e:fire(b,'OnDragStop')
    eq(ns.db.ui.minimap.angle,angle,'center drop leaves angle unchanged')
    ns.Settings.SaveMinimapAngle(45);e.minimapShape='SQUARE';e:emit('DISPLAY_SIZE_CHANGED')
    local point,parent,relativePoint,x,y=b:GetPoint()
    eq(parent,e.Minimap,'reanchored to minimap parent')
    truth(math.abs(x-80)<0.0001 and math.abs(y-80)<0.0001,'square rim respects corners')
    e.GetMinimapShape=nil
    e.Minimap.GetMaskTexture=function() return 'Interface\\Buttons\\WHITE8X8' end
    e:emit('DISPLAY_SIZE_CHANGED')
    local _,_,_,fallbackX,fallbackY=b:GetPoint()
    truth(math.abs(fallbackX-80)<0.0001 and math.abs(fallbackY-80)<0.0001,'mask texture fallback identifies square minimap')
    e.GetCursorPosition=nil
    local beforeMissingCursor=ns.db.ui.minimap.angle
    e:fire(b,'OnMouseDown','LeftButton');e:fire(b,'OnDragStart');e:fire(b,'OnDragStop')
    eq(ns.db.ui.minimap.angle,beforeMissingCursor,'missing cursor API preserves saved angle')
    ns.Settings.SetMinimapShown(false)
    eq(b:IsShown(),false,'hide during idle safe')
    ns.Settings.SetMinimapShown(true)
    local other,loaded=fresh(H.copy(ns.db))
    truth(math.abs(loaded.db.ui.minimap.angle-45)<0.0001,'angle survives reload')
    truth(loaded.Minimap.button:IsShown(),'minimap visibility survives reload')
    eq(b.scripts.OnUpdate,nil,'drag never installs OnUpdate')
end)

group('settings_validation_caps_and_malformed_saved_ui',function()
    local e,ns=fresh({schema=2,mode='balanced',enabled=true,ui={language='en',window={point='INVALID',x=0/0,y=math.huge},minimap={hide='yes',angle=math.huge}},chatEvents={CHAT_MSG_SAY='no'}})
    eq(ns.db.mode,'balanced','malformed UI never alters valid filtering mode')
    eq(ns.db.ui.window.point,'CENTER','bad window point repaired')
    eq(ns.db.ui.window.x,0,'nonfinite window x repaired')
    eq(ns.db.ui.window.y,0,'nonfinite window y repaired')
    eq(ns.db.ui.minimap.hide,false,'bad minimap hide repaired')
    eq(ns.db.ui.minimap.angle,225,'bad minimap angle repaired')
    eq(ns.db.chatEvents.CHAT_MSG_SAY,true,'bad scope boolean repaired')
    eq(ns.Settings.SetMode('unknown'),false,'invalid mode rejected')
    eq(ns.Settings.SetEnabled('false'),false,'invalid toggle rejected')
    eq(ns.Settings.SetDomainPolicy('unknown'),false,'invalid policy rejected')
    eq(ns.Settings.SetChatEvent('CHAT_MSG_GUILD',false),false,'unregistered scope rejected')
    eq(ns.Settings.SaveMinimapAngle(0/0),false,'NaN angle rejected')
    eq(ns.Settings.EditList('allow','add','Bad\nName'),false,'control character name rejected')
    for index=1,100 do truth(ns.Settings.EditList('phrase','add','Entry '..index),'phrase below cap') end
    eq(ns.Settings.EditList('phrase','add','Entry 101'),false,'101st unique phrase rejected')
    eq(H.count(ns.db.phrases),100,'cap respected')
    truth(ns.Settings.EditList('phrase','add','Entry 1'),'existing entry permitted at cap')
    eq(ns.db.mode,'balanced','invalid operations preserve mode')
end)

group('missing_optional_apis_and_ui_errors_do_not_disable_filter',function()
    local e,ns=fresh(nil,{noMinimap=true,noTooltip=true,noBackdropMixin=true})
    eq(ns.Minimap.button,nil,'missing minimap safely skips button')
    eq(ns.installed,true,'chat filter still registered')
    truth(e:chat('mythicstore.com',nil,8001),'missing minimap preserves filtering')
    e:cmd('');truth(ns.UI.frame:IsShown(),'panel still opens without minimap/tooltip')
    eq(e:chat('WTS Copper Bar 2g per stack',nil,8002),false,'normal chat still allowed')
    local bad,failedUI=fresh(nil,{createFrameError=true})
    eq(failedUI.installed,true,'UI creation error leaves filter installed')
    local ok=pcall(bad.cmd,bad,'')
    eq(ok,true,'panel creation failure guarded from slash command')
    truth(bad:chat('mythicstore.com',nil,8003),'panel failure cannot break hide decision')
    eq(bad:chat('LFM healer',nil,8004),false,'panel failure cannot swallow ordinary chat')
    local normal,safe=fresh()
    open(normal,safe,'overview')
    safe.AddChangeListener(function() error('simulated UI listener failure') end)
    truth(normal:chat('mythicstore.com',nil,8005),'listener error cannot change valid filter outcome')
    eq(normal:chat('LFM healer',nil,8006),false,'listener error preserves ordinary chat')
    eq(safe.sessionErrors,0,'UI listener failures are not chat classification failures')
end)

group('native_regions_have_nonnegative_geometry',function()
    local e,ns=fresh()
    open(e,ns,'overview')
    local visited=0
    local function validate(item)
        assert(item:GetWidth()>=0,'negative native region width: '..tostring(item.text or item.kind))
        assert(item:GetHeight()>=0,'negative native region height: '..tostring(item.text or item.kind))
        visited=visited+1
        for _,child in ipairs(item.children or {}) do validate(child) end
    end
    validate(ns.UI.frame)
    truth(visited>100,'all panel native children inspected')
    eq(ns.UI.frame:GetWidth(),760,'reference home width')
    eq(ns.UI.frame:GetHeight(),724,'reference home height')
    local function inside(item,description)
        local x,y,w,h=e:bounds(item,ns.UI.frame)
        truth(x>=0 and y>=0 and x+w<=ns.UI.frame:GetWidth() and y+h<=ns.UI.frame:GetHeight(),description)
    end
    for _,item in ipairs({ns.UI.controls.overviewToggle,ns.UI.controls.overviewBalanced,
        ns.UI.controls.overviewStrict,ns.UI.controls.homeMessages,ns.UI.controls.homeAdvanced,
        ns.UI.controls.close,ns.UI.title,ns.UI.emblem}) do inside(item,'home visible control remains inside frame') end
    for _,key in ipairs({'log','lists','settings','test'}) do
        ns.UI.Show(key)
        eq(ns.UI.frame:GetWidth(),900,'advanced content width: '..key)
        eq(ns.UI.frame:GetHeight(),700,'advanced content height: '..key)
        for _,tab in ipairs({'overview','log','lists','settings','test'}) do inside(ns.UI.controls.tabs[tab],'advanced navigation stays within frame') end
        inside(ns.UI.panels[key],'advanced content stays within frame: '..key)
        inside(ns.UI.controls.backHome,'back home stays within frame')
        local _,footerY,_,footerH=e:bounds(ns.UI.footer,ns.UI.frame)
        local _,panelY,_,panelH=e:bounds(ns.UI.panels[key],ns.UI.frame)
        truth(footerY>=panelY+panelH,'advanced footer clears content: '..key)
        truth(footerY+footerH<=ns.UI.frame:GetHeight()*.938,'advanced footer clears gold frame: '..key)
    end
    e.UIParent:SetSize(800,600);ns.UI.Show('settings')
    truth(ns.UI.frame:GetScale()<1,'small viewport scales native panel')
    truth(ns.UI.frame:GetWidth()*ns.UI.frame:GetScale()<=776,'scaled panel fits horizontal margin')
    truth(ns.UI.frame:GetHeight()*ns.UI.frame:GetScale()<=576,'scaled panel fits vertical margin')
    ns.UI.Show('overview')
    truth(ns.UI.frame:GetWidth()*ns.UI.frame:GetScale()<=776,'home also fits small viewport horizontally')
    truth(ns.UI.frame:GetHeight()*ns.UI.frame:GetScale()<=576,'home also fits small viewport vertically')
    e.UIParent:SetSize(1920,1080);e:emit('DISPLAY_SIZE_CHANGED')
    eq(ns.UI.frame:GetScale(),.72,'visible panel restores compact scale after display grows')
    e.UIParent:SetSize(640,480);e:emit('UI_SCALE_CHANGED')
    truth(ns.UI.frame:GetWidth()*ns.UI.frame:GetScale()<=616,'scale event keeps visible home inside narrow viewport')
    truth(ns.UI.frame:GetHeight()*ns.UI.frame:GetScale()<=456,'scale event keeps visible home inside short viewport')
    eq(e.addCalls,5,'display changes do not reinstall chat callbacks')
    local _,footerY,_,footerH=e:bounds(ns.UI.footer,ns.UI.frame)
    local _,actionY,_,actionH=e:bounds(ns.UI.controls.homeAdvanced,ns.UI.frame)
    truth(footerY>=actionY+actionH,'home footer clears advanced action')
    truth(footerY+footerH<=ns.UI.frame:GetHeight()*.938,'home footer clears gold frame')
end)

group('explicit_fonts_and_button_glyphs_fit_under_global_font_changes',function()
    local e,ns=fresh(nil,{inheritedFontSize=24})
    local checked=0
    for _,tab in ipairs({'overview','settings','lists','log','test'}) do
        open(e,ns,tab)
        local function visit(item)
            if not item:IsVisible() then return end
            if item.kind=='FontString' then
                truth(item.font~=nil,'visible native text has an explicit font: '..item:GetText())
                if item:GetText()~='' and item.maxLines~=1 then
                    local _,_,_,availableHeight=e:bounds(item,ns.UI.frame)
                    truth(item:GetStringHeight()<=availableHeight+.5,'visible text lines fit native region height: '..item:GetText())
                end
            end
            if item.kind=='Button' and item.caption and item.caption:GetText()~='' then
                local caption=item.caption
                local x,y,w,h=e:bounds(caption,item)
                truth(caption:GetUnboundedStringWidth()<=w+.5,'full visible button glyphs fit width: '..caption:GetText())
                truth(caption:GetStringHeight()<=h+.5,'visible button glyphs fit height: '..caption:GetText())
                truth(x>=0 and y>=0 and x+w<=item:GetWidth()+.5 and y+h<=item:GetHeight()+.5,'button caption stays inside control: '..caption:GetText())
                checked=checked+1
            end
            for _,child in ipairs(item.children or {}) do visit(child) end
        end
        visit(ns.UI.frame)
    end
    truth(checked>50,'all panel pages contribute caption fit checks')
    eq(e:fontSize(ns.UI.controls.testInput),12,'local editor ignores enlarged global font object')
    eq(ns.UI.controls.testInput.GetStringHeight,nil,'native editor is not granted a FontString-only method')
end)

group('advanced_controls_stay_inside_content_and_clear_gold_frame',function()
    local e,ns=fresh()
    local checked=0
    for _,tab in ipairs({'log','lists','settings','test'}) do
        open(e,ns,tab)
        local panel=ns.UI.panels[tab]
        local panelX,_,panelWidth=e:bounds(panel,ns.UI.frame)
        truth(ns.UI.frame:GetWidth()-panelX-panelWidth>=50,'advanced content preserves gold frame inset: '..tab)
        for _,item in ipairs(panel.children) do
            if item.kind~='FontString' and item.kind~='Texture' and item.kind~='Line' then
                local x,y,w,h=e:bounds(item,panel)
                truth(x>=-.01 and x+w<=panel:GetWidth()+.01,'advanced control fits content width: '..tab..' / '..tostring(item.fullLabel or item.kind))
                truth(y>=-.01 and y+h<=panel:GetHeight()+.01,'advanced control fits content height: '..tab..' / '..tostring(item.fullLabel or item.kind))
                checked=checked+1
            end
        end
    end
    truth(checked>50,'all four advanced pages contribute control containment checks')
end)

group('compact_scale_close_glyph_and_clean_footer',function()
    local e,ns=fresh()
    local c=open(e,ns,'overview')
    eq(ns.UI.frame:GetScale(),.72,'default native panel is 28 percent smaller')
    truth(math.abs(ns.UI.frame:GetWidth()*ns.UI.frame:GetScale()-547.2)<.001,'compact home has intended visible width')
    eq(ns.UI.shortcut,nil,'footer slash hint removed')
    eq(contains(e:texts(ns.UI.frame),'/fcc'),false,'footer does not render a slash hint')
    eq(c.close.caption,nil,'close icon does not depend on a truncatable character')
    local lines=0
    for _,region in ipairs(c.close.regions) do
        eq(region.kind=='FontString',false,'close glyph has no font string region')
        if region.kind=='Line' or (region.kind=='Texture' and region.rotation) then lines=lines+1 end
    end
    truth(lines>=2,'close icon contains both diagonal strokes')
    local directions={}
    for _,region in ipairs(e:snapshot(c.close)) do
        if region.kind=='Line' then
            local a,b=region.lineStart,region.lineEnd
            truth(a~=nil and b~=nil,'close stroke has two endpoints')
            truth(a[1]>=0 and b[1]<=c.close:GetWidth() and a[2]>=0 and b[2]>=0 and a[2]<=c.close:GetHeight() and b[2]<=c.close:GetHeight(),'close stroke remains inside its hit target')
            local slope=(b[1]-a[1])*(b[2]-a[2])
            directions[slope>0 and 'positive' or 'negative']=true
        end
    end
    truth(directions.positive and directions.negative,'close geometry draws crossing diagonals')
    e:click(c.close);eq(ns.UI.frame:IsShown(),false,'texture close button still closes the panel')
    ns.UI.Show('settings')
    eq(ns.UI.frame:GetWidth()*ns.UI.frame:GetScale(),648,'advanced panel uses same compact scale')
    e.UIParent:SetSize(550,420);e:emit('DISPLAY_SIZE_CHANGED')
    truth(ns.UI.frame:GetScale()<=.72,'compact cap survives smaller display')
    truth(ns.UI.frame:GetWidth()*ns.UI.frame:GetScale()<=526,'smaller advanced panel fits horizontal viewport')
    truth(ns.UI.frame:GetHeight()*ns.UI.frame:GetScale()<=396,'smaller advanced panel fits vertical viewport')
    local fallback,other=fresh(nil,{noCreateLine=true})
    local controls=open(fallback,other,'overview')
    eq(controls.close.caption,nil,'older-client close fallback also avoids font truncation')
    truth(controls.close.closeGlyph and contains(controls.close.closeGlyph.texture,'UI-Panel-MinimizeButton'),'older-client close fallback loads native icon')
    fallback:click(controls.close);eq(other.UI.frame:IsShown(),false,'older-client native icon still closes panel')
end)

group('long_row_labels_elide_but_full_values_and_actions_survive',function()
    local e,ns=fresh(nil,{inheritedFontSize=24})
    local author='Extremely Long Seller '..string.rep('Name ',18)..'-Realm'
    truth(e:chat('mythicstore.com',author,9901),'long-author incoming message hidden')
    local c=open(e,ns,'log')
    local row=c.logRows[1]
    eq(row.entry.author,author,'source log retains full author')
    truth(row.truncated,'long row is deliberately shortened')
    local _,_,captionWidth=e:bounds(row.caption,row)
    truth(row.caption:GetUnboundedStringWidth()<=captionWidth+.5,'shortened row fits its visible width')
    truth(contains(row.fullLabel,author),'full row label retains complete author')
    e:fire(row,'OnEnter')
    local lines={};for _,line in ipairs(e.GameTooltip.lines) do lines[#lines+1]=line[1] end
    truth(contains(table.concat(lines,'\n'),row.fullLabel),'hover exposes complete shortened row')
    e:fire(row,'OnLeave');eq(e.GameTooltip:IsShown(),false,'row tooltip hides when hover ends')
    e:input(c.logSearch,author)
    eq(c.logRows[1].entry.author,author,'search uses full source value')
    e:click(c.logRows[1]);e:click(c.logAllow)
    truth(ns.db.allow[ns.NameKey(author)],'allow action targets complete original author')
    eq(e:chat('mythicstore.com',author,9902),false,'long original author is now allowed')
end)

group('multiline_native_editor_keeps_a_fixed_scrollable_viewport',function()
    local e,ns=fresh(nil,{inheritedFontSize=24})
    local c=open(e,ns,'test')
    local box=c.testInput
    truth(box.multiLine,'local test input is a multiline native editor')
    truth(box.viewport~=nil and box.scroll~=nil,'local test input has a dedicated fixed viewport')
    local initialHeight=box.viewport:GetHeight()
    local session,total,callbacks=ns.sessionBlocked,ns.db.totalBlocked,ns.callbackCount
    e:input(box,'mythicstore.com')
    eq(box.viewport:GetHeight(),initialHeight,'one short line cannot collapse the surrounding input surface')
    truth(initialHeight>=80,'local test viewport provides visible space for multiple lines')
    e:fire(box.viewport,'OnMouseDown','LeftButton')
    truth(box:HasFocus(),'clicking empty viewport focuses its native editor')
    local sample='mythicstore.com\n'..string.rep('A normal extra line\n',35)
    e:input(box,sample)
    eq(box:GetText(),sample,'native editor preserves newlines and complete input')
    eq(box.viewport:GetHeight(),initialHeight,'long input cannot expand over surrounding controls')
    truth(box.scroll:GetVerticalScrollRange()>0,'long native editor content has a scroll range')
    box:SetCursorPosition(#sample)
    truth(box.scroll:GetVerticalScroll()>0,'cursor at bottom is brought into view')
    box:SetCursorPosition(0)
    eq(box.scroll:GetVerticalScroll(),0,'cursor at beginning scrolls back to top')
    e:fire(box.scroll,'OnMouseWheel',-1)
    truth(box.scroll:GetVerticalScroll()>0,'mouse wheel scrolls long native editor input')
    e:fire(box.scroll,'OnMouseWheel',-1000)
    eq(box.scroll:GetVerticalScroll(),box.scroll:GetVerticalScrollRange(),'native editor wheel scroll clamps at bottom')
    e:fire(box.scroll,'OnMouseWheel',1000)
    eq(box.scroll:GetVerticalScroll(),0,'native editor wheel scroll clamps at top')
    e:click(c.testRun)
    truth(ns.UI.lastTest.block,'full multiline sample executes actual classifier')
    eq(ns.sessionBlocked,session,'multiline local evaluation leaves session counter untouched')
    eq(ns.db.totalBlocked,total,'multiline local evaluation leaves saved counter untouched')
    eq(ns.callbackCount,callbacks,'multiline local evaluation does not call incoming chat adapter')
    eq(#ns.log,0,'multiline local evaluation does not create hidden messages')
    eq(e.SendChatMessage,nil,'multiline editor never obtains outbound chat API')
end)

group('footer_feedback_readable_without_covering_content',function()
    local e,ns=fresh()
    open(e,ns,'overview')
    local text='Long setting feedback '..string.rep('with explanation ',12)
    local session,total=ns.sessionBlocked,ns.db.totalBlocked
    ns.UI.SetMessage(text,true)
    eq(ns.UI.footer.maxLines,1,'long footer feedback stays on one native line')
    truth(e:fontSize(ns.UI.footer)<17,'long footer feedback uses smaller native font')
    e:fire(ns.UI.feedbackFrame,'OnEnter')
    truth(e.GameTooltip:IsShown(),'full feedback appears in hover tooltip')
    eq(e.GameTooltip.lines[2][1],text,'tooltip preserves full feedback text')
    e:fire(ns.UI.feedbackFrame,'OnLeave')
    eq(e.GameTooltip:IsShown(),false,'leaving footer hides feedback tooltip')
    eq(ns.sessionBlocked,session,'reading feedback does not count a blocked message')
    eq(ns.db.totalBlocked,total,'reading feedback does not change saved counter')
end)

group('reference_theme_local_textures_and_typography',function()
    local e,ns=fresh()
    open(e,ns,'overview')
    truth(ns.UI.title.font~=nil,'native title uses explicit typeface')
    truth(e:fontSize(ns.UI.title)>=36,'title has reference hierarchy')
    eq(ns.UI.title:GetText(),'Forever Clean Chat','native title preserves addon name')
    local media=ns.UI.media
    truth(type(media)=='table','theme exposes its local asset paths')
    for _,key in ipairs({'frame','emblem'}) do
        local path=media[key]
        truth(type(path)=='string' and contains(path,'Interface\\AddOns\\ForeverCleanChat\\Media\\'),'asset is resolved from addon Media: '..key)
        local relative=path:match('ForeverCleanChat\\(.+)$'):gsub('\\','/')
        local file=io.open(root..'/'..relative,'rb')
        truth(file~=nil,'shipped local texture exists: '..key)
        local header=file:read(18);file:close()
        eq(header:byte(3),2,'local texture is uncompressed true-color TGA: '..key)
        eq(header:byte(17),32,'local texture preserves RGBA: '..key)
    end
    eq(ns.UI.emblem.texture,media.emblem,'visible emblem loads the shipped asset')
    local borderFound=false
    for _,item in ipairs(e:snapshot(ns.UI.frame)) do if item.texture==media.frame then borderFound=true end end
    truth(borderFound,'native panel contains shipped frame ornament')
    eq(contains(e:texts(ns.UI.frame),'INTERFACE CONCEPT'),false,'concept watermark not copied into addon')
    eq(contains(e:texts(ns.UI.frame),'EXAMPLE DATA'),false,'example data watermark not copied into addon')
end)

FCC_UI_RESULT=report
print('UI interactions: '..report.passed..'/'..report.total..' passed on '.._VERSION..'; native rendering and live Forever: NOT RUN')
if report.failed>0 then error('UI interaction failures: '..report.failed) end
